src/asmcnc/comms/router_machine.py
Updated from M3 S12000 to M3 S25000 under spindle_on in the router_machine.py
=> spindle_on speed update

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_lobby.py
Sets LEDs to Blue on powerup, and soft reset
=> Basic lighting

src/asmcnc/skavaUI/widget_network_setup.py
- Set multiline to false in network widget text inputs
- Changed country code entry to GB
=> Set network text inputs with single line entry

LICENSE
Defining the licence for the SmartBench
=> Adding BSD licence

src/asmcnc/skavaUI/widget_developer_options.py
Adding current branch to the Developer tab.
=> Replacing empty label with branch

src/asmcnc/skavaUI/widget_developer_options.py
Using `subprocess` was returning:
```
WindowsError: [Error 2] The system cannot find the file specified
```
in windows. Potentially [this error](https://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call).
Replacing `subprocess.check_output` with `os.popen`.
=> Fix subprocess

src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/widget_developer_options.py
Filechooser screen refresh updated; just needed a different directory to look for ftp files.
Have not checked that it definitely finds files ftp'd across to it. 
Also chucked a "reboot" into the Get SW Update in dev.
=> Filechooser fix

src/asmcnc/comms/serial_connection.py
- Should be able to get an idea of what caused the exception
- Haven't handled in the GUI yet, but will help for dev.
=> Logs an Assertion Error when an exception is thrown related to write to serial failures

src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/popup_stop_press.py, src/main.py
Deleted writeTimeout = 0, but added in an upper limit on read timeout (6 seconds). 
Runs lovely, tested in eclipse with arduino on checking Contourx20 endurance file. Ran test brick through arduino. 
Needs stress testing on machine.
=> Integrated all serial.write into the grbl_scanner while loop. 

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_homing.py, src/main.py
=> Added 5 second pause in homing cycle Gcode between phase 1 and 2

src/asmcnc/skavaUI/screen_safety_warning.py
Please advise if more info needs to be on there.
=> Updated information on safety screen.

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/widget_developer_options.py, src/main.py
=> Explicit implementation of `altDisplayText` for realtime commands

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_homing.py, src/asmcnc/skavaUI/widget_quick_commands.py
=> added Cancel button and moved home all into homing screen itself

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_homing_warning.py, src/asmcnc/skavaUI/widget_developer_options.py, src/asmcnc/skavaUI/widget_quick_commands.py, src/asmcnc/skavaUI/widget_virtual_bed_control.py, src/asmcnc/skavaUI/widget_xy_move.py
- Cleared out Gcode switch
- Added homing warning screen to go datum
- "Double tap" issue reviewed, but not fixed
=> Quick UI fixes

src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_job_done.py, src/main.py
Replaced job done pop up with a job done screen, with working image/button :)
=> Job done pop up

src/asmcnc/skavaUI/screen_final_chance_to_check_gcode.py, src/asmcnc/skavaUI/screen_homing_warning.py, src/asmcnc/skavaUI/widget_quick_commands.py, src/main.py
Think this is set to merge to master,-dev?
Removed compulsory req to grbl-check GCode.
=> Ask to check gcode before go

src/asmcnc/skavaUI/widget_developer_options.py
=> Platform update button

src/asmcnc/skavaUI/widget_developer_options.py
=> Moving reboots in line with git pulls and ansible runs

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/main.py
Honestly I'm loving the branch name puns.
So this little badger has been pulling the wool over everyone's eyes for some time now. A sneaky little nuance in timing accidentally created by "this guy" meant that the z0 position was getting recorded at the end of the decel from the probing operation - *not* the point at which the probe signal was received.
Net result was the z0 positionw as always about 150 microns too low.
Also the z probe plate thickness was hardcoded at 1.65 when actually the plate in use was at 1.53. So we need a dialogue for user to update this value so they can tune on receipt of new plates etc. I'll issue that.
Ok love you bye.
=> A probing investigation

src/asmcnc/skavaUI/widget_developer_options.py
=> Emailing state button

src/asmcnc/skavaUI/widget_developer_options.py, src/main.py
- Virtual HW
- Bake GRBL settings
- Buffer log
=> Commented out superflous (/non-user friendly) dev options

src/asmcnc/skavaUI/screen_developer.py
Updated defaults for MVP release (mostly new ranges and slightadjustment to new Y rack steps/mm)
=> $ setting changes to reflect latest HW

src/asmcnc/skavaUI/widget_settings_options.py, src/main.py
Need to release version immediately after PR merge.
=> Update sw release

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_file_loading.py
moved vac on/off from being appended during file loading to machine commands that are called during job start/end/cancellation
=> fix for issue #192

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_check_job.py, src/asmcnc/skavaUI/widget_gcode_monitor.py
Uses buffer stuffing instead of seq streaming for file checking.
Tidy up of rogue $Cs - now any check toggle should go through machine functions enable check mode and disable check mode. 
Needs some testing with rigorous files on machine prior to merge.
=> Fixes for #145 and hopefully #149

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_check_job.py, src/asmcnc/skavaUI/widget_gcode_monitor.py
Reverts YetiTool/easycut-smartbench#198
=> Revert "Fixes for #145 and hopefully #149"

src/asmcnc/skavaUI/screen_check_job.py, src/asmcnc/skavaUI/screen_file_loading.py, src/asmcnc/skavaUI/screen_home.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_usb_filechooser.py, src/asmcnc/skavaUI/widget_gcode_view.py
Reverts YetiTool/easycut-smartbench#195
=> Revert "File preview lag"

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_file_loading.py
Reverts YetiTool/easycut-smartbench#196
=> Revert "fix for issue #192"

src/asmcnc/skavaUI/screen_check_job.py, src/asmcnc/skavaUI/screen_file_loading.py, src/asmcnc/skavaUI/screen_home.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_usb_filechooser.py, src/asmcnc/skavaUI/widget_gcode_view.py
Reverts YetiTool/easycut-smartbench#203
=> Revert "Revert "File preview lag""

src/asmcnc/calibration_app/screen_backlash.py, src/asmcnc/calibration_app/screen_distance_1_x.py, src/asmcnc/calibration_app/screen_distance_1_y.py, src/asmcnc/calibration_app/screen_distance_2_x.py, src/asmcnc/calibration_app/screen_distance_2_y.py, src/asmcnc/calibration_app/screen_distance_3_x.py, src/asmcnc/calibration_app/screen_distance_3_y.py, src/asmcnc/calibration_app/screen_distance_4_x.py, src/asmcnc/calibration_app/screen_distance_4_y.py, src/asmcnc/calibration_app/screen_finished.py, src/asmcnc/calibration_app/screen_landing.py, src/asmcnc/calibration_app/screen_measurement.py, src/asmcnc/calibration_app/screen_prep_calibration.py
Made minor changes to text and initial movements based on beta testing feedback.
Still needs a sense-checker on the number of steps to set
=> Calibration

src/asmcnc/calibration_app/screen_finished.py, src/asmcnc/calibration_app/screen_prep_calibration.py, src/asmcnc/calibration_app/screen_tape_measure.py
tried to make the tape measure warning screen look nicer. 
failed. 
good enough though.
=> Final calibration edits

src/asmcnc/apps/shapeCutter_app/cut_parameters/sC_job_parameters.py
Patch for bugs in the circle part of gcode generation
=> Circle fix

src/asmcnc/skavaUI/widget_network_setup.py
No need to delete default text any more.
Closes #236
=> Changed TextInputs default text to hint_text

src/asmcnc/skavaUI/widget_settings_options.py
=> Removed dev-level buttons from user-level settings widget

src/asmcnc/apps/shapeCutter_app/cut_parameters/sC_job_parameters.py, src/asmcnc/apps/shapeCutter_app/screens/popup_input_error.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_31.py, src/asmcnc/skavaUI/screen_check_job.py
Error messages now all include details of where boundary conflict arises.
=> Specify bounds

src/asmcnc/skavaUI/screen_door.py, src/asmcnc/skavaUI/screen_homing.py
added extra delay to checking homing is successful
=> Homing fix

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_go.py
Red light persists, but stops flashing at least
=> The case of the red flasher is finally closed

src/asmcnc/apps/wifi_app/screen_wifi.py, src/asmcnc/apps/wifi_app/wifi_documentation.rst
Error handling for if customer enters password less than 8 characters (or more than 63, or anything that linux can't hack).
=> Wifi brick patch

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_homing.py, src/main.py
Moves Z-head to position the X-beam's CoG at the midplane, prior to overdriving into the legs
=> Auto-squaring improvement

src/asmcnc/comms/usb_storage.py, src/asmcnc/geometry/geometry.py, src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_check_job.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_usb_filechooser.py, src/main.py
USB mounting and unmounting was a bit chaotic. 
- Unmount was not actually being called, and if it was then the USB was being mounted again anyway due to a Clock.schedule_once function. 
- get_USB was being put onto a clock schedule interval repeatedly without checking that the USB was already being polled. 
Warnings: 
- Have added some pop-ups to let the user know about USB safety. HOWEVER, USB unmounting can take a while...the pop-ups, while useful, can get pretty annoying. If a long file is loading, it also causes the pop-up to stick which is annoying as heck.
=> USB investigation

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_aperture_island.py, src/asmcnc/skavaUI/screen_door.py, src/asmcnc/skavaUI/screen_go.py, src/asmcnc/skavaUI/screen_homing.py, src/main.py
... to remove the warning "x" in the Eclipse file tree
=> Masked Eclipse import errors: # @UnresolvedImport

src/asmcnc/comms/usb_storage.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_usb_filechooser.py
Closes #246 
Added label below selection so that long filenames can be checked before committing to loading
=> Filechooser now displays icons for easier finger press

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_33.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_36.py
Hard coded. Needs investigation one day - have commented in the code
Closes #351
=> ShapeCutter trace job speed for Imperial job fixed

src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_squaring_manual_vs_square.py
Large info-style popup class added to main `popup_info` module
=> Auto-square decision has info popup to explain decision 

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_go.py, src/asmcnc/skavaUI/widget_speed_override.py
Controls added to the go screen
=> Realtime spindle rpm adjustment enabled!

src/asmcnc/skavaUI/screen_home.py
=> 353 remove joblist container from job screen

src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_go.py, src/asmcnc/skavaUI/screen_home.py
=> After over a year, a progress indicator is now on the go screen

src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_squaring_manual_vs_square.py, src/asmcnc/skavaUI/widget_quick_commands.py
=> Popup if no file loaded but play pressed

src/asmcnc/apps/SWupdater_app/screen_update_SW.py, src/settings/settings_manager.py
Needs git desktop (or a command line) to clone the git repo to a USB stick. 
Then fetches from the USB repo and checks out the latest tag it has. 
Have also tested logic in repo that was only cloned from the USB. 
Need a beta release to fully be confident in functionality. 
Need some refactoring and tidying of pop-ups etc. before release.
=> USB SW update functionality is in

src/asmcnc/skavaUI/screen_developer.py, src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/widget_settings_options.py
- Developer app button in lobby now takes you to existing dev screen
- Dev button & update buttons moved out of pro
=> Developer pre app

src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_usb_filechooser.py, src/asmcnc/skavaUI/widget_gcode_monitor.py
- Added popup on developer app button to warn people away
- Added warning pop-up on gcode monitor
- Put in some clock delays to stop the USB pop-ups from sticking on a large file
=> Popup tidy

src/asmcnc/apps/SWupdater_app/screen_update_SW.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/comms/usb_storage.py, src/asmcnc/skavaUI/screen_go.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_usb_filechooser.py, src/settings/settings_manager.py
- Got rid of hacky filechooser - usb popup delay
- Added in extra wifi safety on git reclone/software repair
- Fixed go screen file lines streamed shapecutter bug
=> Final bits

src/asmcnc/skavaUI/screen_homing_prepare.py
Extended labels so that extraction hose warning shows up
=> Remove extraction hose reminder

src/asmcnc/apps/SWupdater_app/screen_update_SW.py, src/asmcnc/apps/shapeCutter_app/screens/popup_machine.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_filechooser.py, src/asmcnc/apps/wifi_app/screen_wifi.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_alarm.py, src/asmcnc/skavaUI/screen_developer.py, src/asmcnc/skavaUI/screen_error.py, src/asmcnc/skavaUI/screen_home.py, src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/screen_local_filechooser.py, src/asmcnc/skavaUI/screen_mstate_warning.py, src/asmcnc/skavaUI/screen_serial_failure.py, src/asmcnc/skavaUI/widget_gcode_monitor.py
Fixed: 
#418 
#413 
#410 
#408 
#377
#340
#339 
#296
=> Quickie issues

src/asmcnc/skavaUI/widget_z_height.py
- Added dummy Z datum size & position for case where no file is loaded
=> Z datum vis

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_welcome.py
- re-jigged welcome screen/start-up timings again
- set laser datum out of bounds pop-up
=> Pre release bugs/UX improvements

src/asmcnc/apps/SWupdater_app/popup_update_SW.py, src/asmcnc/apps/SWupdater_app/screen_update_SW.py, src/asmcnc/apps/wifi_app/screen_wifi.py, src/asmcnc/skavaUI/screen_developer.py, src/asmcnc/skavaUI/screen_welcome.py, src/main.py, src/settings/settings_manager.py
- removed in-app slowdown (for SW Update app) 
- added refresh button (so updates are manually controlled)
- on start, versions are fetched & checked - user is notified for new version
- added warning for beta releases to discourage people from downloading them
=> Sw update alert

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py
Now software gets confirmation that check is enabled by reading serial output from GRBL.
=> Grbl check check

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_check_job.py, src/asmcnc/skavaUI/screen_file_loading.py
Notify user if feed rates are too low or too high in file check
=> Feed rate file check

src/asmcnc/skavaUI/screen_door.py, src/asmcnc/skavaUI/screen_go.py, src/asmcnc/skavaUI/screen_stop_or_resume_decision.py
Prevented maintenance prompts from coming up if job is paused/doored/cancelled etc.
=> Calibration prompt debug

src/asmcnc/calibration_app/screen_finished.py, src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_developer.py, src/asmcnc/skavaUI/screen_go.py
Remind user in another 320 hours
=> Calibration prompt remind time

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_welcome.py
Moved laser off into bootup sequence, changed time to command, and set default LED to yellow so that when laser off called on startup it doesn't override the LED
=> Laser time

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_go.py
Change the voltage conditions for registering overload: 
Max overload threshold reduced from 4750 to 2500 mV.
=> Spindle patch

src/asmcnc/skavaUI/screen_go.py, src/asmcnc/skavaUI/screen_home.py, src/asmcnc/skavaUI/widget_quick_commands.py, src/asmcnc/skavaUI/widget_z_move.py
Merge in changes that mean if you reset the datum just before loading, it will also clear the reminder.
=> Z datum reminder

src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
If console doesn't have a model file, it triggers the final "else" where there is a variable bug.
=> Patch in factory screen

src/asmcnc/skavaUI/screen_z_head_diagnostics.py
Made some corrections to the z_head_diagnostics. We are having problems with cycling for a refurbished head.
=> Z head diagnostics corrections

src/asmcnc/core_UI/sequence_alarm/alarm_manager.py, src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_1.py, src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_2.py, src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_3.py, src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_4.py, src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_5.py
Reverts YetiTool/easycut-smartbench#602
=> Revert "Alarm screens again"

src/asmcnc/apps/shapeCutter_app/cut_parameters/sC_job_parameters.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_safety_warning.py
Console will now look and test for ports that look like SmartBench, as opposed to trying to connect to any hardcoded port.
=> Serial stability

src/main.py
refactor how main.py checks the config file at start up so that ansible run & release notes screen are called before the config file sets its check flag to false
=> config_ansible_conflict

src/asmcnc/comms/__init__.py, src/asmcnc/comms/serial_connection.py, test/comms_serial_connection_tests/tempsvoltagestest.py
Also contains unit test for temps & voltages with mock serial object (needs mock and serial_mock packages to run)
=> Temperatures and voltages into serial comms

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_go.py, test/comms_serial_connection_tests/spindle_feedback_test.py
4-value Ld: messages are currently just recorded in serial module
=> Parses 4-value Ld: and single-value Ld: messages differently

src/asmcnc/apps/systemTools_app/screens/screen_beta_testing.py
- added ansible run to beta update (i.e platform package manager)
- added wait popup so that user knows their console hasn't just frozen
=> Run ansible on beta update

src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/settings/settings_manager.py
Also add broken and missing to list of errors.
=> Incorporate fsck check into factory reset and factory console update

src/asmcnc/production/database/calibration_database.py, test/database_tests/query_tests.py
- updated db stages
- fixed set_up_connection function
- added unit tests
=> Merge fixes back into dev branch

src/asmcnc/production/database/calibration_database.py, test/database_tests/query_tests.py
- fixed does_final_test_stage_already_exist to work only with insert_final_test_stage function
- more unit tests for final test functions
=> Fixes and further unit tests

src/asmcnc/comms/router_machine.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_home.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_warranty_choice.py, src/z_head_qc_app.py
- disconnect & reconnect Z Heads
- disconnect & reconnect USBs 
- get FW version read-in from USBs
- fix FW read in from Z Head on warranty choice screen
=> Added buttons to ZH QC warranty

src/asmcnc/comms/router_machine.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_1.py
- When grbl settings are baked, $22 needs to be set first otherwise GRBL complains about setting soft limits. 
- Pulled bake grbl settings function from router_machine, so it's same across the board
- Added check in bake grbl settings function before sending $51 or $53 commands
=> Setting error

src/asmcnc/comms/serial_connection.py
New variables setting_51 and setting_53 that store the values of these two new settings
=> Read in settings 51 and 53

src/asmcnc/comms/router_machine.py
save_grbl_settings function in router_machine module now also saves settings 51 and 53, using try-excepts to check if they have values just like setting 50
=> Saves grbl settings 51 and 53

src/asmcnc/apps/systemTools_app/screens/calibration/screen_stall_jig.py, src/asmcnc/comms/router_machine.py
Temporarily expanding ranges beyond max, in order to harvest as much cal check data as possible - even if there's an issue!
=> Cal check range for stall jig

src/asmcnc/comms/router_machine.py, src/asmcnc/production/database/calibration_database.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_connecting.py
On z head qc startup, thermal coefficients are set for every motor alongside current.
=> Thermal coefficients

src/asmcnc/apps/systemTools_app/screens/calibration/widget_current_adjustment.py, src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_1.py
Z head qc (and lower beam qc) motor chips test now uses raw sg values, and expected ranges are adjusted to fit this
=> Z head qc raw sg

src/asmcnc/apps/systemTools_app/screens/calibration/widget_current_adjustment.py
Idle current is now set along with active current in current adjustment screen.
=> Idle current adjustment

src/asmcnc/production/z_head_qc_jig/z_head_qc_pcb_set_up.py
Tested on rig + v1.3 ZH with dual drivers
=> ZH QC updated limits on currents and thermal coefficients

src/asmcnc/production/database/calibration_database.py, tests/integration_tests/database_tests/query_tests.py
- import pymysql as my_sql_client, or raise exception and import MySQLdb as my_sql_client
- updated SNs in tests to be 8888 as we're getting a bit close to making 2222
Tested on both Pi4 + Pi3 with opening DB factory screens, and by running the query tests (on both platforms).
=> Mysql options

ansible/init.yaml
Ansible will look for the relevant bluetooth lines if they exist and remove them. 
Tested on Martha
=> Use ttyS0 port instead of ttyAMA0

src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/asmcnc/apps/systemTools_app/screens/screen_final_test.py
Two new final test screens with placeholder length values, for shortbench
Tested on rig
=> Shortbench final test

src/asmcnc/apps/systemTools_app/screens/calibration/screen_overnight_test.py
tested on machine with usb stick plugged in, without sudo permission is sometimes? denied
=> run with sudo

src/asmcnc/apps/systemTools_app/screens/screen_build_info.py, src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/asmcnc/comms/router_machine.py, tests/automated_unit_tests/comms/test_smartbench_model_detection.py
SmartBench model is now worked out using a function from router_machine rather than read from a file
Tested using unit tests, and functionally tested on windows
=> Version detection

src/asmcnc/comms/router_machine.py
=> reduce minimum temp threshold for tuning by 5 degrees

src/asmcnc/comms/router_machine.py
So that checks for new files can be used by other branches that are currently in development :) 
Tested as part of homing_cal (on rig and machine), and then commit where this functionality was added was cherry picked out. Opened EC on computer as well to make sure cherry pick worked fine :)
=> Cherry picked new file checking from homing_cal branch

src/asmcnc/job/yetipilot/yetipilot.py, tests/automated_unit_tests/job/yetipilot/test_yetipilot_units.py
Bare bones placeholders, so that we can start to populate it :) 
Unit test file for populating as well 
Tested with unit test
=> Prep yetipilot class

src/asmcnc/comms/serial_connection.py, src/asmcnc/core_UI/job_go/widgets/widget_yeti_pilot.py, src/asmcnc/job/yetipilot/yetipilot.py, src/asmcnc/skavaUI/screen_go.py, src/main.py, tests/automated_unit_tests/job/yetipilot/test_yetipilot_units.py
- Set up for YP module in main.py
- Set up some basic functions in the class, including a wrapper function that can be used to schedule feed overrides so that they are automatically stopped/cancelled if the job stops
- Put yp add to stack function under "is job streaming" logic - this ensures that it will only run during a job/file stream
- Add a toggle into YP container to test/set up enable/disable functionality
- Ensure toggle stays on (if it's on) during pause, but if job is restarted then it is off as default
- Ensure toggle matches YP state
- Increased spindle data read-in delay to 1 sec to reduce read-in errors
Tested on rigs and alarms for all job pause/cancel/completion cases:
- Spindle overload
- Alarms
- Doors
- Pause -> Resume
- Pause -> Cancel
- GRBL error
- Job completion …
=> Start/stop YetiPilot

src/asmcnc/skavaUI/screen_file_loading.py
- Tested with a smaller number of lines, and works on rig
- Full test with a 16 mil line file just caused the console to freeze and eventually crash anyway on Pi 3, but I've left the logic in on the off chance it works sometimes. 
- Tested on normal branch to confirm that behaviour with giant file is the same - it is, just crashes and then says "Killed" 😂
- Have a buffer of 10 lines for custom commands that get appended to the job by the SW
=> Throw error and show can't load screen if GRBL file > 10 million lines

src/asmcnc/skavaUI/screen_stop_or_resume_decision.py, tests/manual_tests/visual_screen_tests/screen_stop_or_resume_decision_test.py
Added frontend for information for pause screen when job is paused by yetipilot due to low feed.
Tested on windows with unit test
=> Add text for yetipilot low feed error screen

src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_go.py
Small code change that solves a lot of problems :)
Tested on rig with both dollar settings
=> Only use console saved brush times - not SC2 times

src/asmcnc/core_UI/job_go/widgets/widget_load_slider.py, src/asmcnc/core_UI/job_go/widgets/widget_yeti_pilot.py
Make accidental blue buttons grey. 
Tested on rig
=> Button patch

src/asmcnc/core_UI/job_go/widgets/widget_yeti_pilot.py, src/asmcnc/skavaUI/screen_go.py
=> Ensure that YP settings cog is also disabled when YP not accessible! 

src/asmcnc/comms/router_machine.py, tests/automated_unit_tests/comms/test_router_machine_units.py
Tested via unit test & running SW on PC
=> Add tolerance to get_is_constant_feed_rate function (and unit tests)

src/asmcnc/job/job_data.py, tests/automated_unit_tests/job/test_job_data_units.py
Tested with unit tests & starting app on PC
=> Add +1 to index when scraping feed

src/asmcnc/comms/router_machine.py, tests/automated_unit_tests/comms/test_router_machine_units.py
Tested with unit test & with starting app on PC
=> Add get_grbl_motion_mode function

src/asmcnc/comms/serial_connection.py, tests/automated_unit_tests/comms/test_serial_connection_process_grbl_push.py
Tested with unit tests and on rig with spindle
=> Add inrush counter to serial comms (used by YP)

src/asmcnc/core_UI/job_go/popups/popup_yetipilot_settings.py, src/asmcnc/job/yetipilot/config/profiles.json, src/asmcnc/job/yetipilot/yetipilot.py, src/main.py, tests/automated_unit_tests/comms/test_serial_connection_streaming_units.py, tests/automated_unit_tests/job/yetipilot/test_yetipilot_units.py, tests/manual_tests/visual_screen_tests/go_screen_sc2_overload_test.py, tests/manual_tests/visual_screen_tests/job_pause_tests.py, tests/manual_tests/visual_screen_tests/screen_stop_or_resume_decision_test.py, tests/manual_tests/visual_screen_tests/yetipilot_settings_popup_test.py
=> Translate tools

src/asmcnc/apps/upgrade_app/screen_upgrade.py, src/asmcnc/skavaUI/screen_lobby.py
When upgrading, spindle cooldown settings are now set automatically to an SC2 spindle.
Tested on rig, edge cases tested on windows
=> Upgrade spindle settings

src/asmcnc/skavaUI/screen_nudge.py
=> Raise Z to safe range on nudge screen exit

src/asmcnc/comms/serial_connection.py, tests/automated_unit_tests/comms/test_serial_connection_process_grbl_push.py
Wait 20 statuses before allowing feed adjustments to prevent inrush slowing the job down.
=> Inrush prevention

src/asmcnc/skavaUI/screen_job_recovery.py
Already added scrollable popups in nudge button pull request - this is just for the main screen popup
=> Break up text on line selection screen popup

src/asmcnc/skavaUI/widget_z_height.py
=> Z widget fix: checked out widget z height file from job recovery

src/asmcnc/core_UI/job_go/popups/popup_yetipilot_settings.py, src/asmcnc/job/yetipilot/yetipilot.py
Reorder sequence in which yetipilot options are picked, to start with material type. 
Requires in situ testing
=> Reorder choices

src/asmcnc/core_UI/job_go/widgets/widget_disabled_yeti_pilot.py, tests/manual_tests/visual_screen_tests/go_screen_sc2_overload_test.py
=> Tidy up disabled yp text

src/asmcnc/skavaUI/screen_lobby.py
=> Make upgrade app visible

src/asmcnc/comms/router_machine.py
re Dennis's comments 
Tested on PC
=> Fix for spindle health check write

src/asmcnc/core_UI/job_go/popups/popup_yetipilot_settings.py, src/asmcnc/core_UI/job_go/widgets/widget_yeti_pilot.py
=> Keep yp disabled if coming out of advanced profile before spindle check has run

src/asmcnc/job/yetipilot/config/profiles.json
=> Add units to profile cutter diameter and step downs

src/asmcnc/comms/foreign_dictionary.txt, src/asmcnc/skavaUI/screen_job_recovery.py
Localisation for the letters F and S on position label in line selection screen, as well as the "Undefined" value text
=> Add localisation for feeds/speeds

src/asmcnc/comms/foreign_dictionary.txt, src/asmcnc/job/job_data.py, src/asmcnc/skavaUI/screen_job_recovery.py, tests/automated_unit_tests/job/test_generate_recovery_gcode.py
Added unit tests for job recovery gcode generation, and made changes to gcode generation function that were found through these unit tests.
Tested with unit test
=> Job recovery unit testing

src/asmcnc/comms/serial_connection.py
=> Use grbl_ln instead of g_count to find cancellation line

src/main.py, v242.txt
=> Add release notes and update version numbers

src/asmcnc/comms/router_machine.py, src/asmcnc/production/lowerbeam_calibration_jig/lowerbeam_calibration_1.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_3.py
For this to work, also needed to adjust temperatures. 
Tested LB app on rig
Tested ZH app on rig and ZHQC
=> Reduce warm up for sub-assembly calibration jigs to 1.5 minutes

src/asmcnc/comms/router_machine.py, src/asmcnc/production/z_head_qc_jig/z_head_qc_2.py
Corrections for 110v, unable to test locally as I don't have a 110v spindle. Have tested for 230v.
=> Ft spindle test

src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_save.py, src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/asmcnc/apps/systemTools_app/screens/screen_final_test.py, src/asmcnc/apps/upgrade_app/screen_upgrade.py, src/asmcnc/comms/router_machine.py
=> Add generic function for dollar setting

src/asmcnc/apps/app_manager.py
=> Initialise maintenance app on startup instead of entry

src/asmcnc/apps/systemTools_app/screens/calibration/screen_overnight_test.py
Follow up from #1191 
Tested on Dev B.
=> Remove redundant brackets

src/asmcnc/skavaUI/screen_home.py
Tested on rig
Should be the opposite of [this PR](https://github.com/YetiTool/easycut-smartbench/pull/1198/files) :)
=> Uncomment job recovery button

.coveragerc, .gitignore, tests/README.md
=> Add test readme inc notes on using coverage, and coverage config file

tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Changes based on feedback given in https://github.com/YetiTool/easycut-smartbench/pull/1216
=> Refactor visual tests feedback

src/asmcnc/apps/wifi_app/screen_wifi.py
The code actually links to the correct file name now!!!!!
=> fixed typo

src/asmcnc/skavaUI/widget_status_bar.py
Tested in on a v1.3 bench and v1.2 rig
=> Limit switch indicator

src/main.py, v264.txt
=> Update version numbers and release notes

src/asmcnc/apps/app_manager.py, src/asmcnc/apps/maintenance_app/screen_maintenance.py, src/asmcnc/apps/shapeCutter_app/screen_manager_shapecutter.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_20.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_22.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_23.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_24.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_25.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_dimensions.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_post_job_save.py, src/asmcnc/apps/systemTools_app/screen_manager_systemtools.py, src/asmcnc/apps/systemTools_app/screens/popup_system.py, src/asmcnc/apps/systemTools_app/screens/screen_build_info.py, src/asmcnc/apps/systemTools_app/screens/screen_system_menu.py, src/asmcnc/apps/upgrade_app/screen_upgrade.py, src/asmcnc/apps/wifi_app/screen_wifi.py, src/asmcnc/keyboard/custom_keyboard.py, src/asmcnc/skavaUI/screen_home.py, src/asmcnc/skavaUI/screen_job_feedback.py, src/asmcnc/skavaUI/screen_job_recovery.py, src/main.py, tests/manual_tests/visual_screen_tests/screen_maker.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
This significantly improves performance as far as I can tell :) 
Tested with visual screen tests, and on rig.
=> Set up one keyboard object and pass it to all the screens, instead of making a new one every time

tests/manual_tests/experiments/experiment_custom_keyboard.py
=> Update keyboard test file to work with changes to how object is initialised

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_11.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_21.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_23.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_24.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_26.py, src/asmcnc/calibration_app/screen_measurement.py
=> Updates to shape cutter and calibration app to make sure the other font is still ok

src/asmcnc/apps/systemTools_app/screen_manager_systemtools.py, src/asmcnc/apps/systemTools_app/screens/calibration/screen_current_adjustment.py, src/asmcnc/apps/systemTools_app/screens/calibration/screen_serial_numbers.py, src/asmcnc/apps/systemTools_app/screens/calibration/screen_set_thresholds.py, src/asmcnc/apps/systemTools_app/screens/screen_beta_testing.py, src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/asmcnc/apps/systemTools_app/screens/screen_final_test.py
Otherwise some of the symbols don't seem to load properly on the default keyboard, which is quickly irritating.
Tested on PC and test rig.
=> Set up dev/factory area keyboards as well

src/asmcnc/skavaUI/screen_job_incomplete.py, src/main.py
Tested on windows - ensuring each input works correctly (int/str, single line/multiline)
=> Use custom keyboard on job incomplete screen

src/asmcnc/apps/app_manager.py, src/asmcnc/apps/start_up_sequence/start_up_sequence_manager.py, src/asmcnc/apps/start_up_sequence/warranty_app/screen_manager_warranty.py, src/asmcnc/apps/start_up_sequence/warranty_app/screens/screen_warranty_registration_3.py
Tested on rig with visual screen tests
=> Ensure activation code text input brings up custom keyboard as well

src/asmcnc/comms/foreign_dictionary.txt, src/asmcnc/job/yetipilot/config/profiles.json
Tested through visual screen tests & on Martha
=> Solid surface translations

src/main.py
Checked out from scale_automation_base. 
Tested on Mac.
=> Add width and height to main.py

src/asmcnc/comms/router_machine.py, src/asmcnc/skavaUI/screen_lobby.py, tests/automated_unit_tests/comms/test_smartbench_model_detection.py
- Show ShapeCutter normally
- Show DrywallTec app if dwt.txt is present above EC-SB folder. 
Tested on PC & rig, and with unit tests :)
=> Drywall app visibility

src/asmcnc/apps/drywall_cutter_app/config/config_classes.py, src/asmcnc/apps/drywall_cutter_app/config/config_loader.py, src/asmcnc/apps/drywall_cutter_app/config/cutters/test_cutter.json, src/asmcnc/apps/drywall_cutter_app/config/cutters/test_cutter2.json, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, tests/automated_unit_tests/apps/dwt/test_dwt_config.py
PR Details:
- Functional cutter dropdown
- Improvements to dwt_config module, including new function get_available_cutter_names() and debugging decorator.
- Unit test for get_available_cutter_names()
Tested on rig.
=> DWT Cutter Dropdown

src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
PR Details:
- File chooser for DWT app, hooks into dwt_config module to load config in.
Tested on rig
=> DWT Config Filechooser

src/asmcnc/keyboard/custom_keyboard.py
=> Use default keyboard if on macOS

src/asmcnc/apps/drywall_cutter_app/config/config_classes.py, src/asmcnc/apps/drywall_cutter_app/config/configurations/test_config.json, tests/automated_unit_tests/apps/dwt/test_dwt_config.py
=> Add 'rotation' param to config

src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py, src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
PR Details:
- Adds the save config screen
Tested on rig
=> DWT Config Saving Filechooser

src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py, src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py
The sort_json function was breaking the json display in the file choosers so I've temporarily removed it.
Tested on rig.
=> Remove broken sort_json function

src/asmcnc/apps/drywall_cutter_app/config/config_loader.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, tests/automated_unit_tests/apps/dwt/test_dwt_config_checking.py
=> Check config files are valid before loading them

src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py
=> Limit file name to 40 characters

src/asmcnc/comms/router_machine.py
=> Set fast probe speed to 400

src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Rotation parameter is now assigned in the JSON when any rotation is performed
=> Drywall canvas rotation config

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
Show only toolpaths available for current cutter
=> Drywall cutter toolpath list

src/main.py
Force aspect ratio for XL console
Tested on XL console
=> Force aspect ratio using BoxLayout

src/asmcnc/apps/systemTools_app/screens/screen_system_menu.py
Benji accidentally pushed commits to master, this undoes them.
=> Revert master

tests/manual_tests/visual_screen_tests/visual_screen_tests.py
app.height and app.width need to be defined for screens to work
Tested on windows and c10
=> Fix visual screen tests for c10

tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Missed resolution and aspect ratio stuff
Tested on c10
=> Actually fix visual tests for c10

src/asmcnc/apps/upgrade_app/screen_already_upgraded.py
=> C10 dk screen already upgraded

src/asmcnc/apps/upgrade_app/screen_upgrade_successful.py
=> Checkout file from scaled_black

src/asmcnc/apps/start_up_sequence/screens/screen_reboot_to_apply_settings.py
=> C10 dk screen reboot to apply settings

ansible/init.yaml
This is the fix for the text colour bug on Pi4.
Tested on a fresh platform on my rig.
=> Bootloader upgrade

src/asmcnc/apps/start_up_sequence/screens/screen_release_notes.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
=> C10 dk screen release notes

src/asmcnc/apps/start_up_sequence/screens/screen_starting_smartbench.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
=> C10 dk screen starting smartbench

src/asmcnc/skavaUI/screen_mstate_warning.py, src/asmcnc/skavaUI/widget_quick_commands.py
Tested on both console sizes in all languages.
=> Scale mstate_warning screen

src/asmcnc/skavaUI/screen_jobstart_warning.py, src/main.py
=> Scale jobstart_warning

src/asmcnc/skavaUI/screen_boundary_warning.py, src/asmcnc/skavaUI/widget_quick_commands.py, src/main.py
Tested on both consoles in all sizes.
=> Scale boundary warning screen

src/asmcnc/skavaUI/screen_file_loading.py, src/main.py
=> Scale file loading screen

src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/screen_rebooting.py
=> Scale rebooting screen

src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/screen_serial_failure.py, src/main.py
=> Scale serial failure screen

src/asmcnc/skavaUI/screen_diagnostics.py, src/main.py
Tested on both consoles in all languages (don't think it's localised though)
=> Scale diagnostics screen

ansible/init.yaml, ansible/requirements.yml
NOT TO BE MERGED INTO MASTER
Tested on C7 and C10
=> Expand filesystem from ft branch

src/asmcnc/skavaUI/screen_tool_selection.py, src/main.py
Tested on both consoles in all screen sizes.
=> Tool selection screen

src/asmcnc/skavaUI/screen_nudge.py, src/main.py
Dennis has his name against the widgets so I haven't touched them.
=> Nudge screen scaling

src/asmcnc/skavaUI/screen_spindle_cooldown.py, src/main.py
=> Spindle cooldown screen

src/asmcnc/skavaUI/screen_lift_z_on_pause_decision.py, src/main.py
=> Z Lift on pause screen

src/asmcnc/skavaUI/screen_check_job.py, src/main.py
=> Check job screen

src/asmcnc/skavaUI/screen_homing_active.py, src/main.py
=> Homing active screen

src/asmcnc/skavaUI/screen_job_incomplete.py, src/main.py
=> Job incomplete screen

src/asmcnc/skavaUI/screen_job_recovery.py, src/main.py
Tested on all screen sizes and all languages
=> Job recovery screen

src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_3.py
=> C10 bp screen alarm 3

src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_4.py
=> Reviwed screen_alarm_4.py

src/asmcnc/apps/systemTools_app/screens/calibration/screen_set_thresholds.py
=> C10 bp screen set thresholds

src/asmcnc/calibration_app/screen_prep_calibration.py
=> C10 la calibration app screen prep calibration

src/asmcnc/calibration_app/screen_finished.py
=> Auto scaled calibration finished screen

src/asmcnc/calibration_app/screen_wait.py
=> Auto scaled calibration app wait screen

src/asmcnc/calibration_app/screen_backlash.py
=> C10 la calibration app screen backlash

src/asmcnc/calibration_app/screen_distance_1_x.py
=> C10 la calibration app screen distance 1 x

src/asmcnc/calibration_app/screen_distance_2_x.py
=> Auto scaled screen_distance_2_x

src/asmcnc/calibration_app/screen_measurement.py
Tested on C7 & C10 for all cases
=> auto-scaled screen measurement

src/asmcnc/apps/systemTools_app/screens/calibration/screen_calibration_test.py
=> Reviewed & restored comments in screen_calibration_test.py

src/asmcnc/calibration_app/screen_distance_2_y.py
=> C10 la calibration app screen distance 2 y

src/asmcnc/calibration_app/screen_distance_3_x.py
=> Auto scaled screen_distance_3_x

src/asmcnc/calibration_app/screen_distance_4_x.py
=> Auto scale screen_distance_4_x

src/asmcnc/calibration_app/screen_distance_3_y.py
=> Auto scale screen_distance_3_y

src/asmcnc/calibration_app/screen_distance_4_y.py
=> C10 la calibration app screen distance 4 y

src/asmcnc/skavaUI/screen_lobby.py
=> C10 vp screen lobby

src/asmcnc/skavaUI/screen_squaring_active.py
Tested on C7 & C10 in all languages
=> Scaled screen squaring active

src/asmcnc/skavaUI/screen_homing_prepare.py
Tested on C7 & C10 in all languages, had to manually set the default font to scale.
=> C10 Screen homing prepare

src/asmcnc/skavaUI/screen_spindle_shutdown.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Tested on C7 & C10, in all languages, with screen test (& also did full function test on C7)
=> C10 screen spindle shutdown

src/asmcnc/apps/systemTools_app/screens/screen_build_info.py
Still to do: popups
Tested on C7 & C10
=> C10 la screen build info

src/asmcnc/core_UI/popups.py, src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/screen_stop_or_resume_decision.py
=> Add different popup classes

src/asmcnc/apps/start_up_sequence/warranty_app/screens/screen_warranty_registration_1.py
=> C10 dk screen warranty registration 1

src/asmcnc/apps/start_up_sequence/data_consent_app/screens/wifi_and_data_consent_3.py
=> C10 dk wifi and data consent 3

src/asmcnc/skavaUI/screen_job_feedback.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Tested on C7 & C10, in all languages.
Added screen test for ease of testing, and checkout out visual_screen_tests file from other branch that's in PR to avoid merge conflicts. 
Had to add size hints & a box layout around the batch number text box because text was getting cut off on the big screen, even though everything was scaled as expected. 
Left out comments that I thought were no longer needed, think I only copied one across.
=> C10 screen job feedback

src/asmcnc/core_UI/popups.py, src/asmcnc/skavaUI/screen_homing_decision.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Tested on C7 & C10
The popup is still a bit janky because the info symbol is not scaling, but will proof & fix this separately.
=> C10 screen homing decision

src/asmcnc/core_UI/popups.py
=> Fix generic error popup

src/asmcnc/skavaUI/screen_recovery_decision.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Tested on C7 & C10 for all cases
Popup not covered yet.
=> C10 scale screen_recovery_decision

src/asmcnc/apps/start_up_sequence/screens/screen_safety_warning.py
Checked out this file from the original safety warning screen as that branch had changes for other files too.
=> Scale safety warning screen

src/asmcnc/skavaUI/screen_squaring_manual_vs_square.py
=> Scaled screen_squaring_manual_vs_square.py

src/asmcnc/apps/upgrade_app/screen_upgrade.py, src/asmcnc/core_UI/popups.py
=> Scaled error popups

src/asmcnc/apps/start_up_sequence/data_consent_app/screen_manager_data_consent.py
=> C10 dk wifi and data consent 3 popup

src/asmcnc/core_UI/popup_manager.py, src/asmcnc/core_UI/popups.py, src/asmcnc/skavaUI/screen_lobby.py, src/main.py
To make it easier to build our basic popup types. Stored in the screen manager for easy access in screens.
=> Popup manager

src/asmcnc/apps/wifi_app/screen_wifi.py
=> C10 bp screen wifi

src/asmcnc/core_UI/popups.py
Tested using popup test system
=> Add update font size function

src/asmcnc/apps/SWupdater_app/popup_update_SW.py, src/asmcnc/apps/SWupdater_app/screen_update_SW.py
=> C10 bp popup update sw

src/asmcnc/skavaUI/screen_squaring_manual_vs_square.py, src/main.py
Tested on C10 & C7 in all languages
=> C10 la screen manual square font size

src/asmcnc/keyboard/custom_keyboard.py
=> C10 la keyboard

src/asmcnc/skavaUI/widget_gcode_monitor.py
=> Scale font size of gcode monitor text input

src/asmcnc/skavaUI/popup_nudge.py
=> C10 bp popup nudge.py

src/asmcnc/core_UI/custom_popups.py, src/asmcnc/core_UI/popup_manager.py, src/asmcnc/core_UI/popups.py
- Getting these in first to build upon. 
- Note that I did need to resolve conflicts between Archie & Vlad's branches, namely the wait popup implementation.
=> Core UI popup classes & popup manager

src/asmcnc/core_UI/popups.py
=> button layout padding

src/asmcnc/core_UI/popup_manager.py
=> show popup info height correction

src/asmcnc/core_UI/popup_manager.py
=> Added reboot after popup open

src/asmcnc/core_UI/custom_popups.py, src/asmcnc/core_UI/popups.py
=> Select popup fixes

src/asmcnc/skavaUI/screen_lobby.py
There is no "Remind me" text entry, should be "Remind me later"
=> Fix remind me text

src/asmcnc/apps/maintenance_app/widget_maintenance_z_misc_save.py
=> Changed popup to mini popup

src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_save.py
=> Widget maintenance spindle save fix

src/asmcnc/skavaUI/widget_virtual_bed_control.py, src/main.py
Scaled font. Tested on console 7 + 10
=> C10 bp widget virtual bed control

src/asmcnc/core_UI/job_go/widgets/widget_yeti_pilot.py
=> enable stretch on yetipilot cog

src/asmcnc/apps/systemTools_app/screens/screen_support_menu.py, src/asmcnc/apps/systemTools_app/screens/screen_system_menu.py
border is necessary to stop image distortion
=> Fix image and text scaling

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_tutorial.py
=> C10 dk screen shape cutter tutorial

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_dimensions.py
=> C10 dk screen shape cutter dimensions

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_15.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC15_xy_move.py
=> Checkout files from scaled_black

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_17.py
=> C10 dk screen shape cutter 17

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_20.py
=> C10 dk screen shape cutter 20

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_22.py
=> C10 dk screen shape cutter 22

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_24.py
=> C10 dk screen shape cutter 24

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_25.py
=> C10 dk screen shape cutter 25

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_28.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC28_xy_move.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC_virtual_bed.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC_work_coordinates.py
=> C10 dk screen shape cutter 28

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_31.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC31_xy_move.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC31_z_height.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC31_z_move.py, src/asmcnc/apps/shapeCutter_app/screens/widget_sC31_z_setgo.py
=> C10 dk screen shape cutter 31

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_post_job_save.py
=> C10 dk screen shape cutter post job save

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_repeat.py
=> Cheeckout file from scaled_black

src/asmcnc/skavaUI/widget_gcode_view.py
=> Reinstate comments from pull 1425

src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_health_check.py
=> Allowed the toggle image to stretch to increase size

src/asmcnc/skavaUI/screen_lobby.py
=> Show shapecutter on big console

src/asmcnc/comms/usb_storage.py, src/main.py
usb_storage.py merged from c10_aj_popups and c10_aj_popups_vp. Tested on C10
=> Usb storage fixes

src/asmcnc/job/job_data.py, src/asmcnc/skavaUI/screen_job_recovery.py, tests/automated_unit_tests/job/test_generate_recovery_gcode.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2540)
Job recovery now includes R gcode in the list of possible gcodes
=> Job recovery r handling

src/asmcnc/apps/SWupdater_app/popup_update_SW.py, src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py, src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py, src/asmcnc/apps/maintenance_app/popup_maintenance.py, src/asmcnc/apps/shapeCutter_app/screens/popup_info.py, src/asmcnc/apps/shapeCutter_app/screens/popup_input_error.py, src/asmcnc/apps/shapeCutter_app/screens/popup_machine.py, src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_aperture_island.py, src/asmcnc/apps/start_up_sequence/data_consent_app/screens/popup_data_wifi_warning.py, src/asmcnc/apps/start_up_sequence/warranty_app/screens/popup_warranty.py, src/asmcnc/apps/systemTools_app/screens/calibration/widget_sg_status_bar.py, src/asmcnc/apps/systemTools_app/screens/popup_system.py, src/asmcnc/apps/systemTools_app/screens/widget_final_test_xy_move.py, src/asmcnc/comms/router_machine.py, src/asmcnc/production/lower_beam_qc_jig/widget_lower_beam_qc_xy_move.py, src/asmcnc/production/z_head_qc_jig/popup_z_head_qc.py, src/asmcnc/skavaUI/popup_info.py, src/asmcnc/skavaUI/screen_help.py, src/asmcnc/skavaUI/screen_lobby.py, src/asmcnc/skavaUI/widget_gcode_view.py, src/asmcnc/skavaUI/widget_quick_commands.py, src/asmcnc/skavaUI/widget_virtual_bed_control.py, src/asmcnc/tests/calibration_buttons_test.py, src/main.py, tests/manual_tests/experiments/experiment_toggle_reset_pin.py
Removed '# @UnresolvedImport' comment from all files.
=> Remove '# @UnresolvedImport' comment

src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_24.py
=> Give more width to text in popup

src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Automatically converts rectangles to squares when both length inputs are equal
=> Drywall canvas square conversion

src/asmcnc/keyboard/custom_keyboard.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2655?atlOrigin=eyJpIjoiZmY1ZDE2MjVjY2U0NDI4M2FiNGJkYTYxYjcyOWE0ZWUiLCJwIjoiaiJ9)
The keyboard now handles selected text properly when deleting/overwriting
=> Added logic to handle deletion of selected text

src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2668?atlOrigin=eyJpIjoiOThiYTQ5ZjA1YmVkNGEyYTllZjkzZmExZjI1YjRjYTciLCJwIjoiaiJ9)
=> Updated depth per pass text logic

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2661)
Changes to improve canvas text inputs, including switching to using float correctly, allowing user to input mistakes so they can delete them manually, and only checking inputs after they are unfocused. Also refactored the input change functions into a single function.
=> Dwt canvas fix text inputs

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2658)
Added a switch to the bottom right of the canvas that lets the user select between mm and inches
=> Drywall canvas units

src/asmcnc/apps/start_up_sequence/warranty_app/screen_manager_warranty.py, src/asmcnc/apps/start_up_sequence/warranty_app/screens/screen_warranty_registration_1.py, src/asmcnc/apps/start_up_sequence/warranty_app/screens/screen_warranty_registration_2.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/jira/software/projects/YTSS/boards/1?assignee=5f8db15e6bc6340068c0bfc3&selectedIssue=YTSS-2447)
- x ] I have completed a self review
=> Archie/dwt rebrand/warranty sequence

src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/asmcnc/comms/model_manager.py, src/asmcnc/comms/serial_connection.py, src/asmcnc/skavaUI/screen_lobby.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2444)
=> decide weither upgrade should be shown or not

src/asmcnc/comms/model_manager.py
=> fixed overwriting of product_code

src/asmcnc/comms/grbl_settings_manager.py, src/asmcnc/comms/model_manager.py, src/asmcnc/comms/serial_connection.py, src/main.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2699)
=> Handle machine specific settings

src/asmcnc/comms/grbl_settings_manager.py, src/asmcnc/comms/model_manager.py, src/asmcnc/core_UI/path_utils.py
=> fixed usage of path_utils

src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-1998)
Updated the bottom slider to a fixed height, to fix the bottom rail of the slider looking cut off. Also updated visual test suite with new stuff to make it work
=> Fix slider graphic

src/asmcnc/apps/systemTools_app/screens/screen_build_info.py, src/asmcnc/comms/model_manager.py
=> fixed crash in system info when no machine was connected.

src/asmcnc/core_UI/components/buttons/probe_button.py, src/asmcnc/skavaUI/screen_home.py
Z datum reminder not getting dismissed after probing with the new probing screen
Quick patch for bug affecting all customers
=> Implement Z datum reminder dismiss

src/asmcnc/apps/wifi_app/screen_wifi.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2679?atlOrigin=eyJpIjoiMTYzNzQ2YmNjMDNkNGNjY2I5MWViNGE4NWYyYWJkOTEiLCJwIjoiaiJ9)
=> Increased timeout timer to 45s

src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2689?atlOrigin=eyJpIjoiYTg2Yzk0YTc0YjBlNDdjNGExNmY1ODRjMGYyMWJiZmQiLCJwIjoiaiJ9)
=> Defocusing all text inputs on popup dismiss

src/asmcnc/comms/grbl_settings_manager.py
=> fixed wrong grbl system settings. added default values for rigs.

v284.txt
=> typo in v284.txt

src/asmcnc/apps/drywall_cutter_app/config/config_loader.py
removes the .json from the preview for cutter_type
=> remove .json for cutter_type in the preview

src/asmcnc/apps/drywall_cutter_app/engine.py, src/asmcnc/apps/drywall_cutter_app/test_engine.py
Reinstate get_custom_shape_extents & tidy & fixes
=> Reinstate get_custom_shape_extents & tidy

src/asmcnc/apps/drywall_cutter_app/engine.py
=> Fix path utils usage

src/asmcnc/apps/drywall_cutter_app/config/config_loader.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py, src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py, tests/automated_unit_tests/comms/test_serial_connection_process_grbl_push.py
removed the 0.1 schedule for check_datum_and_extents() and replaced it with events.
=> removed first 0.1s schedule

src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py, src/asmcnc/comms/model_manager.py, src/asmcnc/comms/router_machine.py, src/main.py
=> fixed smartbench name for drywall

src/asmcnc/skavaUI/screen_home.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2820)
=> Disable job recovery on drywall machines

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py, src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
listening to x,y events properly by scheduling the update function.
check_zh_datum allows for 0.01mm deviation
=> listening to x,y events again. scheduling the call instead of calling it myself.

src/asmcnc/apps/drywall_cutter_app/engine.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
material values are loaded when screen is loaded.
=> go_screen now shows config name (e.g. "My pretty circle")

src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
=> toolpath_offset is only overwritten if invalid for current shape.

src/asmcnc/apps/drywall_cutter_app/engine.py, src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
changed material settings will call on_parameter_change
=> adjusted cutter selection for geberit shape.

src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py, src/asmcnc/core_UI/components/text_inputs/float_input.py, src/asmcnc/core_UI/components/text_inputs/max_length_input.py
=> Add max_length_input.py for use in float_input.py for DWT

src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_90deg.json, src/asmcnc/apps/drywall_cutter_app/engine.py, tests/test_engine.py
=> fixed cut direction for 'on'. fixed 90° cutter toolpath offsets

src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py, src/asmcnc/core_UI/components/text_inputs/float_input.py
=> FloatInput can now be restricted to positive value only

src/asmcnc/apps/drywall_cutter_app/config/config_loader.py, src/asmcnc/apps/drywall_cutter_app/image_dropdown.py
=> Fixed the order of cutters

src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
=> Show max values for X,Y in validation popup

src/asmcnc/keyboard/custom_keyboard.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2702?atlOrigin=eyJpIjoiOGM2ZDY5YWM5ZmFhNDg0NGJiNDcwZmViMGVjZGYyMjciLCJwIjoiaiJ9)
=> Fixed input focus logic

src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
=> Fixed popup loading and error verification

src/asmcnc/apps/drywall_cutter_app/engine.py
=> Added partoff flag for geberit

src/asmcnc/keyboard/custom_keyboard.py
=> Added automatic keyboard positioning

src/asmcnc/apps/start_up_sequence/data_consent_app/screen_manager_data_consent.py
Add missing import (causing crash)
=> Import logger

src/asmcnc/apps/systemTools_app/screens/screen_build_info.py, src/asmcnc/comms/localization.py
Only allow English for DWT and replaced "PrecisionPro +" with "SmartCNC"
=> Only english for dwt

src/asmcnc/comms/router_machine.py, src/asmcnc/comms/serial_connection.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2746)
=> Refactor router machine and serial connection logging

pull_request_template.md
=> removed the spreadsheet from the PR template. Added task for milestone

src/asmcnc/job/yetipilot/config/profiles.json
=> Updated profiles.json

src/asmcnc/comms/serial_connection.py
=> fixed verbose output

pull_request_template.md
=> add language testing to PR template

src/asmcnc/apps/maintenance_app/widget_maintenance_general_settings.py, src/asmcnc/comms/model_manager.py, src/asmcnc/comms/user_settings_manager.py, src/main.py, tests/automated_unit_tests/comms/test_user_settings_manager.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2759)
UserSettingsManager reads/writes a json file containing user settings. widget elements (like Switch) can bind on changes to update.
Unittests provide 100% code coverage
=> UserSettingsManager

src/asmcnc/apps/app_manager.py, src/asmcnc/skavaUI/screen_lobby.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2994)
Removed shapecutter app and any loading for it. DWT now displays on any machine
=> Show dwt on non dwt machines

src/asmcnc/apps/drywall_cutter_app/image_dropdown.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py, src/main.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/jira/software/projects/YTSS/boards/1/backlog?assignee=5f8db15e6bc6340068c0bfc3&issueParent=12987&selectedIssue=YTSS-3001)
I just did a quick run through of scaling properties throughout the DWT app, it's not perfect yet, and there are places I haven't touched, but it's a good start so we can test on C10 aswell as C7.
=> Start of scaling up DWT for C10

tests/manual_tests/experiments/experiment_toggle_reset_pin.py
No ticket
- ~[ ] I have set the recent milestone~
- ~[ ] I have tested graphical changes on all languages~
- ~[ ] I have updated the jira ticket~
- ~[ ] I have updated documentation (if applicable)~
- ~[ ] I have run the unit tests suite and they pass~
=> Make experiment toggle test work again

src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_6mm.json
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2984?atlOrigin=eyJpIjoiMTFjYzVkNTJjNjM0NGZhYjk3NTYxYmE0MzA5ZTY4OWUiLCJwIjoiaiJ9)
=> updated flute length and max_depth_total for tool_6mm.json

src/asmcnc/apps/drywall_cutter_app/config/config_classes.py, src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json, src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2997?atlOrigin=eyJpIjoiNDdiNDBlNTgwYmQ5NDBkNDlhMzhhYWIzZjU2YWY4YzYiLCJwIjoiaiJ9)
=> Added tabs setting to material setup popup

src/asmcnc/apps/drywall_cutter_app/config/config_classes.py, src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json, src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
This reverts commit ab5c35b49a667497bbe4e70c18b85f49f5dc0152, reversing changes made to a594a2289e10988dd4ecf65316a4304655f58a14.
=> Revert "Merge pull request #1737 from YetiTool/vp/tabs"

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/skavaUI/widget_quick_commands.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2983?atlOrigin=eyJpIjoiYTY3OTZlNjNlZmEzNDcxZmFmMmQ2N2FhYzgzOTEwYWQiLCJwIjoiaiJ9)
=> default to router in dwt app

src/asmcnc/skavaUI/screen_file_loading.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3009)
Valid .dwt files have to contain a specific ID as a comment in the gcode. If it doesn't, the file is not loaded, and an error popup is shown.
=> Dwt file validation

src/asmcnc/core_UI/components/buttons/hold_button.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/jira/software/projects/YTSS/boards/1?assignee=5f8db15e6bc6340068c0bfc3&selectedIssue=YTSS-2953)
- Fix hold button on spindle power on popup for all languages.
=> Fix hold button for German/other languages

src/asmcnc/core_UI/components/buttons/hold_button.py
-- see PR for archie/fix_hold_button
=> Fix hold button

src/asmcnc/apps/drywall_cutter_app/engine.py, src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2993?atlOrigin=eyJpIjoiNzAyZjM2ZTRiNWY3NGRlY2I3YWRkNzQ2ZTNiMDE1YWUiLCJwIjoiaiJ9)
Enabled & fixed finishing pass for rectangles, squares & circles as per specification [here](https://docs.google.com/document/d/1jAWaz-my-IGv0Thd8g9llB1wqzDWbs_hcovb-gVNUJg/edit#heading=h.a7pkv9gi6mb4)
None
=> Benji/shapes lite/add finishing pass

src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Changed title from cutting depths to settings
=> Change cutting depths popup title

src/asmcnc/core_UI/utils/color_provider.py
"Import from typing" wrapped in try-except to prevent software crash if typing is not installed. Already in master, but needs pulling onto hotfix branch. 
~- [ ] I have tested graphical changes on all languages~
~- [ ] I have updated the jira ticket~
~- [ ] I have updated documentation (if applicable)~
~- [ ] I have run the unit tests suite and they pass~
~- [ ] [#<pull_request_number>]~
=> Put fix for typing package onto hotfix branch

v290.txt
~- [ ] I have set the recent milestone~
~- [ ] I have tested graphical changes on all languages~
~- [ ] I have updated the jira ticket~
~- [ ] I have updated documentation (if applicable)~
~- [ ] I have run the unit tests suite and they pass~
~- [ ] [#<pull_request_number>]~
Just did a quick beta update test on a rig to make sure adding the file doesn't break anything - I have not re-tested the logic that will use this file.
=> Add v290 file for completeness (and so I can screenshot for docs)

src/asmcnc/apps/maintenance_app/widget_maintenance_z_move.py, src/asmcnc/skavaUI/widget_gcode_monitor.py
[Jira Ticket 1](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2972)
[Jira Ticket 2](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2973)
Updated gcode monitor and maintenance laser tab info popups to include dust shoe safety info. Not localised.
=> Dust shoe safety update popups

src/asmcnc/skavaUI/screen_dust_shoe_alarm.py, src/main.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2761)
Created a dust shoe plug alarm screen that appears when the setting is enabled and the dust shoe is detected unplugged during a job or when spindle is enabled. Visually, the screen is currently just a copy of the door screen.
=> Dust shoe alarm screen

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py, src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3047?atlOrigin=eyJpIjoiYjliMmRiYzhmOTgzNDUxZDg5MDlhODFkNTlhNWQxNDIiLCJwIjoiaiJ9)
Manually defocused all text inputs and manually ran the function which verifies that inputs are correct before a job is run.
=> Updated how the shape dimensions get checked

src/asmcnc/apps/drywall_cutter_app/config/config_loader.py, src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
The description of the auto pass checkbox changed from "Auto pass" to "Auto pass depth".
=> Changed "Auto pass" to "Auto pass depth"

src/asmcnc/skavaUI/screen_yeticut_lobby.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3064)
Resized apps on yeticut lobby screen to match size of apps on main lobby
=> Resize apps on yeticut lobby screen

src/asmcnc/apps/drywall_cutter_app/engine.py
Remove datum offset for line cutting
Lines were being positioned on the sheet with an offset of size (datum x, datum y) This has been changed back to 0 as datuming is handled by SB
None
=> Benji/shapes lite/line datum fix

src/asmcnc/apps/drywall_cutter_app/config/config_classes.py, src/asmcnc/apps/drywall_cutter_app/config/config_loader.py, src/asmcnc/apps/drywall_cutter_app/config/configurations/test_config, src/asmcnc/apps/drywall_cutter_app/config/migration/tool_migration_0_1.json, src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json, src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py, src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py, src/asmcnc/job/database/profile_database.json, src/asmcnc/job/database/tool_database.json
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3044?atlOrigin=eyJpIjoiMmVhNzM1Yjg3OTJjNDFkZjlhOTRjMTliYWQ0MDliMDAiLCJwIjoiaiJ9)
Old DWT configs now get automatically detected and converted to the new format. A version tag is also added to keep track of the version of the config. Files selected in the filechooser are also automatically converted before being displayed.
=> Updated handling of config to update to new version automatically

src/asmcnc/skavaUI/screen_go.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3042)
Use active profile and cutter for yetipilot profile selection
=> Use active profile and cutter for yetipilot profile selection

src/asmcnc/skavaUI/screen_serial_failure.py, tests/manual_tests/visual_screen_tests/visual_screen_tests.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3060)
Added back to lobby button to serial failure screen, not localised
=> Add back to lobby button to serial failure screen

src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py, src/asmcnc/skavaUI/screen_lobby.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3081)
Removed yeticut lobby
=> Remove yeticut lobby

src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Align text input backgrounds better vertically for scaled up shapes
=> Align input canvas heights better

ansible/host_vars/localhost, ansible/init.yaml, src/asmcnc/keyboard/custom_keyboard.py
- Japanese: Install mozcpy & mecab & dependencies
~- [ ] I have set the recent milestone~
~- [ ] I have tested graphical changes on all languages~
~- [ ] I have updated the jira ticket~
~- [ ] I have updated documentation (if applicable)~
~- [ ] I have run the unit tests suite and they pass~
~- [ ] Not applicable~
~- [ ] Own computer~
~- [ ] Console 7"~
~- [ ] Console 10"~
=> Japanese: Install mozcpy & mecab & dependencies

src/asmcnc/job/database/material_database.json, src/asmcnc/job/database/profile_database.json, src/asmcnc/job/database/tool_database.json, src/asmcnc/job/yetipilot/config/profiles.json
Added trespa profiles & made all profiles available on all machines
=> Add trespa profiles & make all profiles available on all machines

src/asmcnc/apps/systemTools_app/screens/screen_beta_testing.py
=> Fix it to 2.9.2
