YetiTool/easycut-smartbench

- src/asmcnc/skavaUI/widget_developer_options.py
- src/main.py
New button in dev screen to fire a bunch of settings to grbl. Whilst this is possible via typing it all into the gcode console, that process has destroyed many a soul. Why have cotton when we can have serial silk.
> Fire grbl a list of $ settings which define the standard hardware setup.

- src/asmcnc/comms/router_machine.py
- src/asmcnc/comms/serial_connection.py
- src/asmcnc/skavaUI/screen_homing.py
- src/asmcnc/skavaUI/screen_safety_warning.py
- src/asmcnc/skavaUI/widget_developer_options.py
- src/asmcnc/skavaUI/widget_quick_commands.py
Changed how we handle the two different homing cases.
* Homing screen now checks serial_comm's `is_sequentially_streaming` flag to know whether it's still homing or not. 
* Squaring routing now uses the `G4 P<x>` grbl delay command to force a 'blocking ok' which guarantees that that machine is idle before issuing $ commands. This replaces a ton of fragile code which was checking for states etc.
* Serial_comms now has a function cancel sequential streaming as a precaution
> Magic square axis fix

- src/asmcnc/comms/router_machine.py
Previous commands would screw up ok counting on during streaming.
So using realtime '&' command which makes lights white as a better than nothing.
> Restores LEDs from flashing red to white on resume

- src/asmcnc/skavaUI/screen_developer.py
Removed the XYZ axis calibration settings which get applied during a grbl settings bake.
Updated value for X axis speed to suit mechanical harmonics
> bake_grbl_settings: rm $= xyz steps/mm; updated $= x max rate

- src/asmcnc/skavaUI/screen_check_job.py
- src/asmcnc/skavaUI/screen_file_loading.py
- src/asmcnc/skavaUI/screen_home.py
- src/asmcnc/skavaUI/screen_local_filechooser.py
- src/asmcnc/skavaUI/screen_usb_filechooser.py
- src/asmcnc/skavaUI/widget_gcode_view.py
Fixes: 
- #194 filters gcode and nc files in the USB filechooser as well
- #193 added try-except clauses around and in the preview function to handle errors
- #155 added in a max line break to the get_non_modal_gcode function when it is used for preview; line cap flags means that this break does not happen when function is being used to detect boundary conflicts. 
- increased max preview lines. this number is really down to preference, so please let me know if want more or less preview lines.
> File preview lag

- src/asmcnc/skavaUI/screen_check_job.py
- src/asmcnc/skavaUI/screen_file_loading.py
- src/asmcnc/skavaUI/screen_home.py
- src/asmcnc/skavaUI/widget_gcode_view.py
- Moves getting non_modal gcode into file loading screen - this then means that bounding box is only defined once
- Moving this into file loading means no cap is needed on number of lines as there isn't a lag on the home screen
- This means that the bounding box is accurate and based on full gcode
> Bounding box fix

- src/asmcnc/skavaUI/widget_gcode_monitor.py
- Stops kivy from idling/freezing/lagging
- Addition of a status update monitor in the settings tab > gcode monitor.
- Have modified how text was stored in the scrollview label for gcode monitor and implemented in status monitor: originally it was one long continuously bloating string, now it is a list, and obsolete elements are deleted. 
- When status is not updating due to machine being in alarm state, status widget tells user "Please reset for status updates". This prevents screen from lagging during alarm state, and is also useful.
> Double monitor

- src/asmcnc/calibration_app/screen_distance_2_y.py
- src/asmcnc/calibration_app/screen_distance_4_x.py
- src/asmcnc/calibration_app/screen_distance_4_y.py
- src/asmcnc/calibration_app/screen_finished.py
- src/asmcnc/calibration_app/screen_landing.py
- src/asmcnc/calibration_app/screen_prep_calibration.py
- src/asmcnc/skavaUI/screen_homing.py
- added in some checks to prevent screens being re-made if they already exist
- routed homing cancellation via the calibration _complete screen, so that any leftover screens get cleared up even in the event of an alarm screen being triggered
> Final calibration edits

- src/asmcnc/skavaUI/widget_virtual_bed_control.py
In Pro, from virtual map tab, removes obsolete view buttons. Adds whitespace between "set" and "go" functions to reduce risk of mis-commands.
> Remove obsolete buttons from map (#257)

- src/asmcnc/apps/shapeCutter_app/cut_parameters/sC_job_parameters.py
- src/asmcnc/skavaUI/screen_file_loading.py
Lines containing this M06 will get dropped from the job_file.
(Previously "M6" *was* caught, but some protocols export this as M06, so the cmd was sneaking through).
Closes #220
> Added "M06" to blacklist of gcode lines

- src/asmcnc/skavaUI/widget_gcode_monitor.py
Replaced `var = string` to `var = array` 
Closes #274
> Clear btn on gcode monitor clears but bricks its output

- src/asmcnc/skavaUI/widget_gcode_monitor.py
It was a trouble maker, and who needs that
Closes #273
> Drop `start up` btn from gcode monitor

- src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_filechooser.py
- src/asmcnc/skavaUI/screen_local_filechooser.py
- src/asmcnc/skavaUI/screen_usb_filechooser.py
Img preview was defunct anyway, so dropped for both local and usb filechoosers.
Now bigger space for longer filenames.
Also dropped switch on the usb filechooser which was designed to delete the file from the usb stick after copying it to the console. It was dangerous (caused crashes) as wasn't used enough to fix.
Closes #282
> Drop img preview container in filechoosers and dangerous usb 'clean on move'

- src/asmcnc/skavaUI/screen_home.py
Dropped `Network` Accordian item from Settings tab in Pro
Closes #295
> Destroy obsolete network widget

- src/asmcnc/comms/router_machine.py
- src/asmcnc/skavaUI/screen_error.py
- src/temp_refactor_notes
Delayed LED strobing calls got mixed into the stream if user was very fast in getting to the go button. FIx: check `is_job_streaming`
Also, on triggering a gcode error screen, the machine would not stop. Fix: `_stop_all_streaming` in `m.stop_from_gcode_error`
> Fast screen switching caused gcode error, also error handling did not stop stream

- src/asmcnc/comms/usb_storage.py
- Current USB module only looks for devices named "sda1" in /dev/, but devices may be named sdb1, sdc1, etc. 
- Have altered module so that now if it doesn't find sda, it looks for sdb/c/d/etc.
> Other usb device names

- src/asmcnc/skavaUI/screen_local_filechooser.py
- src/asmcnc/skavaUI/screen_usb_filechooser.py
- Enabled local & USB folder visibility: Closes #366 
- Removed ./ line in usbstick load file dialogue: Closes #223 
- Indicated filetypes shown: Closes #214
> Filechooser improvements: enabled folders, filetype info and dodged crash ./ line

- src/asmcnc/skavaUI/screen_check_job.py
- src/asmcnc/skavaUI/screen_file_loading.py
- src/asmcnc/skavaUI/screen_go.py
- src/asmcnc/skavaUI/screen_home.py
Fixed for all screens displaying the job name. Closes #359
> 359 remove path names from all displays

- src/asmcnc/comms/router_machine.py
- src/asmcnc/comms/serial_connection.py
- src/asmcnc/skavaUI/screen_safety_warning.py
- src/asmcnc/skavaUI/screen_welcome.py
- src/main.py
This was a deep dive on initialising `serial_communications`
As a result we now have clarity on when different elements are called upon during boot.
These elements get called in the new "Welcome screen"
Sequence is as follows:
- Only called `on_enter` of welcome screen, starting services - delayed to ensure that all kivy functions are complete and clock schedules don't get flattened
- Start services calls `reset_on_alarm` as part of its routine
Also a lot clearer in `serial_connection` as to what's going on (fewer inter-module calls)
> Serial refactoring

- src/asmcnc/skavaUI/screen_welcome.py
Turns out the hard boot timings are a bit longer than soft boot timings, on the pi. So after all that serial comms refactoring, I never tested the final use case, which needed a second longer for the blue LEDs to process!
> Boot timing adjustment to enable blue LEDs

- src/asmcnc/comms/router_machine.py
- src/asmcnc/comms/serial_connection.py
- src/asmcnc/skavaUI/popup_info.py
- src/asmcnc/skavaUI/screen_developer.py
- src/asmcnc/skavaUI/screen_go.py
- src/asmcnc/skavaUI/screen_welcome.py
- src/asmcnc/skavaUI/widget_quick_commands.py
- Currently don't have product codes, but all logic is in place for when we know what they are
- Added password protection into dev screen for "toggle dev mode" 
- If dev mode is on, then spindle overload widget is displayed regardless of product code :)
> Hide spindle overload for non-pro users

- src/asmcnc/skavaUI/screen_developer.py
- Fixed, can now download journalctl logs onto a memory stick (comes out as smartbench_logs.txt)
> Download logs

- src/main.py
- src/settings/settings_manager.py
Use of start_screen variable had been replaced by self.sm.current = 'welcome' in main.
Also refactored some of the pc alert code into functions and added under check config. 
Should all work again now, although will need testing with a bona fide software update.
> Power cycle screen fix

- src/asmcnc/comms/usb_storage.py
I can't do much more to fix the "Repair drive" issue that some people are seeing, wondering if it's an incompatibility between linux/windows/the format of their USB drive.
> Have put extra second delay before telling user its safe to remove their USB stick

- src/asmcnc/comms/router_machine.py
- src/asmcnc/skavaUI/popup_info.py
- src/asmcnc/skavaUI/screen_developer.py
- src/asmcnc/skavaUI/screen_go.py
- src/asmcnc/skavaUI/screen_lobby.py
Options in dev screen to:
- disable reminders
- set all values to full
- Factory reset maintenance values
Factory resetting maintenance values sets everything back to default or zero values, and sets the trigger of a Welcome pop-up that tells users to set up their machines before first use.
> Maintenance prompt overrides & start-up message

- src/asmcnc/comms/serial_connection.py
- src/asmcnc/skavaUI/screen_check_job.py
set this to cancel stream depending on where serial is in streaming process, instead of forcing an all-purpose cancel.
> End of check

- src/asmcnc/core_UI/sequence_alarm/alarm_manager.py
- src/asmcnc/skavaUI/screen_door.py
- src/asmcnc/skavaUI/screen_error.py
- Change UI instances of "stop bar" to "interrupt bar"
- Hid stop/resume buttons from door screen until job can be cancelled or resumed.
> Interrupt bars

- src/asmcnc/comms/router_machine.py
- src/asmcnc/skavaUI/screen_homing_active.py
After homing, if the laser is enabled SB moves back to minimum position that laser datum can still be used (as when setting the datum with laser crosshair, SB will jog towards home for a distance of the laser-spindle offset). 
This minimum position from home is the summation of the laser offset value, a safety from the limit switches, and a positional tolerance.
> Homing laser offset

- src/asmcnc/skavaUI/screen_local_filechooser.py
Filechooser crashing when scrolling while USB banner appears/disappears, fixed by only allowing banner to change state when the user is not touching the filechooser
> Filechooser crash

- src/asmcnc/apps/SWupdater_app/screen_update_SW.py
Currently, if user tries to update SW and it's already up-to-date, the please wait popup doesn't go away! Then console needs a hard restart to clear it - obvs not ideal
Has been catching out production, so hoping this fix will help reduce git repo failure rate.
> Dismiss updating popup if SW is up to date, needs testing

- src/asmcnc/apps/maintenance_app/widget_maintenance_brush_save.py
- src/asmcnc/apps/maintenance_app/widget_maintenance_z_misc_save.py
2 bugfixes:
- Clicking save in the touchplate offset tab in maintenance with an input outside of the permitted range now only shows 1 popup, rather than 2 as it did before
- Clicking save in the brush monitor tab in maintenance with an empty input field no longer crashes the console
> Maintenance bugfixes

- src/lb_calibration_app.py
- src/lower_beam_qc_app.py
- src/z_head_cycle_app.py
- src/z_head_qc_app.py
Platform has been changed so that pi now uses ttyAMA0 port as default, which makes some of the set up instructions obsolete.
> Tidying up set up comments for production jigs

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_overnight_test.py
- src/asmcnc/apps/systemTools_app/screens/calibration/screen_serial_numbers.py
- src/asmcnc/comms/router_machine.py
- test/protocol_tests/calibration_tuning_tests.py
- Sets TOFF and SGT parameters explicitly when data is downloaded from database and uploaded to Z Head
- Does tuning as part of the final test recalibration
> Overnight cal fix

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_overnight_test.py
- src/asmcnc/comms/router_machine.py
- For whatever reason, at end of final test, when the machine goes straight into the tuning, it would accelerate from a position very close to the end jog position, and then overshoot into the limits. 
- Bug wouldn't show if tuning & recal was started from button push, or if first part of final test goes straight into tuning. Might be some issue with processing other commands (e.g. REPORT RAW SET) causing a micro lag or something, not sure. 
- Anyway, moving SB away from it's landing position and then back fixes the problem!
> Prevent alarm between end of first part of final test and tuning

- src/asmcnc/apps/systemTools_app/screens/screen_final_test.py
Brief: 
On FT B2 screen on final test could you do a correction for Y command; from y1637.9 to y1636.9. Thanks
And x1149.2 to x1149.1
> correct board dimensions for FT2 screen, as per Dragos' request

- src/asmcnc/production/z_head_qc_jig/z_head_qc_1.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_2.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_8.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_home.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_warranty_choice.py
Every screen that has a checkbox now has an additional function called reset_checkboxes which clears ticks and crosses, and is called every time serial connection is reconnected
> Resets all checkboxes upon reconnection

- src/asmcnc/production/z_head_qc_jig/z_head_qc_3.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_8.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_home.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_warranty_choice.py
Whenever z head reconnection is performed, an additional function reset_timer is called which resets the calibration timer on z_head_qc_3 back to 30 minutes and stops the current countdown, so that a new countdown can be started when the screen is entered again.
> Reset calibration timer when reconnecting z head

- src/asmcnc/comms/motors.py
- src/asmcnc/comms/router_machine.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_connecting.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_warranty_choice.py
- test/automated_tests/test_router_machine_units.py
- Also ensured that registers and FW/HW versions are cleared/reset when serial is disconnected and reconnected (as Z Head will change) 
- Ensure that "Z Head connecting" screen (which also sets the current) comes up after reconnection called from warranty screen as well as after full QC
> Set Z current to 25 when v1.3 Z Heads are plugged into QC jig

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_stall_jig.py
- Give user the ability to change the minimum threshold if they want (NB: currently, this will not change the minimum threshold used to set the travel (i.e. the first crash to find stall position))
- Minor bug fix: if axis has already been tested, and is being retested after a previous axis, reset the travel_to_stall_pos to none (this ensures that the next part of the test knows the axis has changed).
- Minor bug fix: If there is no detect or overshoot of position, don't auto-start back off
> Stall jig change threshold

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_stall_jig.py
- If SmartBench stalls on the way back to a limit switch (i.e. when it's not supposed to), register this as a false stall and automatically resume the test. 
- If a false stall is detected, that counts as a test fail, and therefore the result is not logged in the database.
> Stall jig: detect false stalls

- src/asmcnc/apps/shapeCutter_app/screen_manager_shapecutter.py
- src/asmcnc/comms/serial_connection.py
- src/asmcnc/job/job_data.py
- src/asmcnc/skavaUI/screen_file_loading.py
- src/asmcnc/skavaUI/screen_home.py
- src/asmcnc/skavaUI/screen_job_recovery.py
- src/asmcnc/skavaUI/screen_nudge.py
- src/asmcnc/skavaUI/screen_recovery_decision.py
- Completing a job now stores info about the job, so that the job can be quickly repeated even if recovery isn't needed
- Jobs are now loaded through job recovery, so the correct job does not need to be loaded to perform job recovery
- Z datum reminder reset in job recovery (through loading screen)
- Shapecutter job info no longer gets stored in recovery file
> Job recovery redo

- src/asmcnc/skavaUI/screen_go.py
When calculating percentage, job_recovery_offset is now taken away from the numerator and denominator, so that if job recovery is active then the current progress is accurately displayed. (if not, then job_recovery_offset has a value of 0 so still will be accurate)
> Show accurate progress percentage

- src/asmcnc/production/z_head_mechanics_jig/z_head_mechanics.py
- src/asmcnc/production/z_head_mechanics_jig/z_head_mechanics_manual_move.py
Added text inputs to manual move screen to allow user to customise current in both phases of the test. The current is also displayed on the main screen whenever it is changed
> Up down jig current input

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_stall_jig.py
- Get and print TMC registers inbetween settings changes, and beginning of stall jig. This is where we normally start to see issues. 
- Tested on dev machine, up to "INSTALL JIGS" part of test (so it does the print, and then that's it :))
> Enhanced tmc print

- src/asmcnc/apps/systemTools_app/screens/screen_system_menu.py
Swapped reboot and support buttons on system tools, so that accidentally double clicking the system tools button puts you on the support screen rather than rebooting
> Swapped buttons

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_overnight_test.py
We were seeing intermittent gcode errors in overnight test, between recalibration stage and full calibrated run stage. 
This was caused by setting the datum prior to file streaming, which also had LED commands sent on a clock. These LED commands then interfered with the file stream, causing a gcode error 😳
> Final test yellow screens

- src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_connecting.py
- src/z_head_qc_app.py
The test will now only run for 5 seconds whereas before it could run for a while if the machine was in an awkward position.
Tested on rig using lower beam qc app. Tested at each limit and in-between.
> Lower beam 'check motor-chips' optimisation

- src/asmcnc/comms/serial_connection.py
- tests/manual_tests/visual_screen_tests/go_screen_sc2_overload_test.py
Added functionality to serial comms to update internal overload value using killtime when SC2 spindle is in use, to be displayed on the go screen
> Digital spindle overload

- ansible/templates/set-hostname.sh
If Pi4, serial has leading 100000*..., and Pi 3 has leading 000000*. For pi 4, prepend a 4 onto last 8 digit of SN to differentiate it from pi 3 SNs. 
Consequences: pi4 hostnames will be 9 characters instead of 8.
> Set different hostnames for pi4 and pi3

- src/asmcnc/core_UI/sequence_alarm/alarm_manager.py
- src/asmcnc/core_UI/sequence_alarm/screens/screen_alarm_1.py
Split text on stall alarm screen into two paragraphs to improve readability
Tested with unit tests for alarm screen
> Split alarm text with newlines

- src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_1.py
LBQC: Motor chips test only uses individual motors and combined value is ignored
ZHQC: Motor chips test uses either individual or combined depending on which how many drivers are in use, and never both
Tested on rig
> Raw sg test fixes

- src/asmcnc/production/database/payload_publisher.py
- tests/automated_unit_tests/comms/test_running_data_measurement.py
Tested via unit test:
def test_publishing_sample_data(running_data_element):
running_data_list = [running_data_element]*10
cdb = CalibrationDatabase()
cdb._process_running_data(running_data_list, "ys60000")
publisher = DataPublisher("ys60000")
response_stall_data = publisher.run_data_send(*cdb.processed_running_data["9"])
assert response_stall_data
Uninstalled pika and paramiko individually to test :) 
also did a test in interactive python from src folder to make sure csv_path was still working normally (had to add the bit that adds the ./src for the unit test to work)
> Package protect

- src/asmcnc/skavaUI/screen_go.py
Fixed bug that would show a negative job progress percentage at the start of a job.
If the recovery offset is calculated as being positive then it is ignored in the percentage calculation. This will at most be 4-5 lines so shouldn't affect the percentage much (and will work more like it does without job recovery)
Tested on windows with arduino
> Stopped calculating negative percentage

- src/asmcnc/comms/serial_connection.py
- src/asmcnc/job/job_data.py
When cancelling a job, recovery info is written if more than 30 seconds have passed since the start of the job, even if the cancel line is less than 0. This means that files that calculate the cancel line incorrectly (i.e. file containing G2/G3) will still have recovery info saved.
Tested on rig
> Always write to recovery file if enough time has passed

- ansible/host_vars/localhost
- ansible/init.yaml
- I know that python-pigpio is installed twice (once with the auto package installer, once with pip). This is important - the auto package installer needs to find pip for python 2 on the pi 4 system, otherwise the specified pip package installer doesn't work. I'm not really sure why. 
-- It is possible to configure ansible to know what path to look for, but these are in different places on pi 3 and 4 so
- matplotlib and numpy install a bit weirdly and differently on each system - this very specific configuration of installing numpy and then mpl means we can keep versions consistent across platforms :) 
- have tried to specify versions where possible and where important. 
Tested on virgin Pi 4 and Pi 3 with factory SD card
NB: PACKAGE INSTALL COULD TAKE A WHILE DURING NEXT SW UPDATE IN …
> Making ansible installs compatible with both Pi 3 and Pi 4

- src/asmcnc/calibration_app/screen_backlash.py
- src/asmcnc/calibration_app/screen_distance_1_y.py
- src/asmcnc/calibration_app/screen_distance_3_y.py
- src/asmcnc/calibration_app/screen_measurement.py
Removed all instances of hardcoded Y length values that are accessible to the user and replaced them with values based on grbl setting 131.
> Make calibration app Y length neutral

- src/asmcnc/comms/serial_connection.py
- src/asmcnc/skavaUI/screen_recovery_decision.py
When a file is being loaded from the job recovery decision screen, the file load is skipped if the file is already loaded.
(This also includes a fix to my last change which included a call to the update_machine_runtime function before the cancellation line is recorded, which resulted in line 0 always being saved)
> Skip file load in job recovery if file is already loaded

- src/asmcnc/calibration_app/screen_backlash.py
The $J caused an error when sent with sequential streaming, now that a pause has been added when $ commands are sent. 
Tested on rig
> Move relative commands don't need to be sent as jogs in cal app

- src/asmcnc/calibration_app/screen_backlash.py
- src/asmcnc/calibration_app/screen_distance_1_y.py
- src/asmcnc/calibration_app/screen_distance_3_y.py
- src/asmcnc/calibration_app/screen_measurement.py
Calibration app needed absolute values in order to work properly. 
Tested on ShortBench
Tested on rig with $131=2502
> Set absolute values for both benches that are length neutral or dependent on length

- src/asmcnc/skavaUI/screen_job_recovery.py
Job recovery GO XY button now raises Z axis to a safe height before performing the XY movement. This additional movement is also performed before the XY movement before moving onto the nudge screen.
Tested on rig, with datum set regularly and set too high
> Raise Z to safe height on GO XY

- src/asmcnc/skavaUI/screen_job_recovery.py
Holding down the gcode scroll button on job recovery line selection screen now scrolls continuously after a short delay
Tested on windows by spamming buttons a lot
> Make holding scroll button scroll indefinitely

- src/asmcnc/apps/systemTools_app/screens/screen_beta_testing.py
> whitespace is stripped in user input anyway, but operators will still delete it if it's there so also strip from when branch put into textbox

- src/asmcnc/production/z_head_mechanics_jig/popup_z_head_mechanics.py
- src/asmcnc/production/z_head_mechanics_jig/z_head_mechanics.py
Up down jig has two new popups:
- When calibrate button is pressed, a popup is shown to tell user to remove the belt before calibration
- When phase one ends, a popup is shown that warns the user before phase two starts
> Up down jig popups

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_current_adjustment.py
- src/asmcnc/apps/systemTools_app/screens/calibration/widget_current_adjustment.py
- Ensure that currents are only reset when: 
- User presses Reset currents button
- User presses Factory settings button
- Currents are NOT reset if there is an alarm/stop bar/grbl error, but that's fine because it will return to the screen. 
- Change reset_current function to only update labels if the current setting has been successful 
- Add a grbl reset button to the screen
> Reset currents only if Idle

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_set_thresholds.py
When modifying the current adjustment screen, and the popup for storing TMC values, I didn't realise that the threshold setting screen used the same popup. As a result, the mods didn't go into the other screen! 
I've added the additional argument and functions to get it to work. 
It could probably do with a little bit of refactoring, but I'm under time pressure and need to finish setting thresholds on the Y rack cutter so that will need to happen another time :) 
(I've also checked that those are the only two screens using this popup currently)
> Needed to patch store tmc values popup on threshold setting screen

- ansible/init.yaml
Patch: consoles with no network that are going from v2.1 -> v2.2 are not changing the port, and this is causing issues in field!
- Added "ignore error" lines to blocks that may fail & block the rest of the playbook if no network is present. 
- Move local EC config plays to much earlier in the playbook, so that even if later blocks fail these still run :) 
Tested on rig with and without network, and with network disabled and mysqldb package completely purged from the system.
> Ensure ansible runs fully on consoles with no connection

- src/asmcnc/apps/systemTools_app/screens/calibration/screen_calibration_test.py
Tested on test rig
Moved logic that inserts the final test stage into the database into its own function, and then call this during the "send data" phase instead of on test start
> Insert test stage into db on data send instead of test start

- src/asmcnc/apps/maintenance_app/screen_maintenance.py
- src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_save.py
- src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py
- src/asmcnc/comms/router_machine.py
On the spindle cooldown settings tab in the maintenance app, selecting a spindle from the dropdown and saving now sets the $51 setting depening on whether or not the spindle is SC2. Additionally, the option to select an SC2 spindle is only given when the PRO+ unlock file and setting 51 both exist.
$51 command is sent every time, regardless of whether it needs changing or not - Boris confirmed that this is fine, as EEPROM wear happens: 'Only when writing different value. This applies to most EEPROMs in the market.
Atmega EEPROM "has an endurance of at least 100,000 write/erase cycles" (from datasheet)
"Write" means wirting "0" in one bit,  "Erase" means write "1"s to all bits in the byte or multiple bytes
Meaning that writing $51=1 when $51 is 0 will cause mupltiple bytes erase and …
> Auto set setting 51

- src/asmcnc/comms/serial_connection.py
- src/asmcnc/skavaUI/screen_go.py
- src/asmcnc/skavaUI/widget_feed_override.py
- tests/automated_unit_tests/comms/test_serial_connection_process_grbl_push.py
Tested on rig, and tested with unit tests
Default override value set to 100
> Read out feed override & report to go screen

- src/asmcnc/comms/router_machine.py
- tests/automated_unit_tests/comms/test_router_machine_tuning_and_calibration.py
Tested on dev machine by adding True flag to force it into clock schedule condition, and checked with logs. Then removed test code & confirmed that homing sequence was working normally again :)
> Syntax bug fix in prep_triple_axes_calibration

- src/asmcnc/skavaUI/screen_go.py
A container is now shown or hidden depending on whether machine is PRO+ or not, which will be used to contain controls for yetipilot.
Tested on rig (including stylus mode)
> Yetipilot enable button

- src/asmcnc/comms/serial_connection.py
- tests/automated_unit_tests/comms/test_serial_connection_process_grbl_push.py
- Put it in to read the line number after it reads in the buffer block, just because this matches the order it'll run in the for loop/matches the order that grbl reads it out
- Unit tests for possible cases
Have set the default line number value to None, but maybe it should be set to 0? Depends on usage.
Also thought about whether it needs resetting between jobs, but this also depends on usage, so have left it. 
Could also overwrite grbl_ln with "None" if no Ln block is present in the status? Again, depends on usage. 
Tested via unit test
Tested on rig with branch line_readin_test (which has dynamic_line_numbers branch merged into it, so that line numbers would be present)
Tested on rig as just this branch :)
> Read in line number from status

- src/asmcnc/comms/router_machine.py
- src/asmcnc/job/job_data.py
- tests/automated_unit_tests/comms/test_router_machine_units.py
- tests/automated_unit_tests/job/test_job_data_units.py
- Slight refactor of functions pulled from YP branch:
- Used a variation of Dennis's code for scraping feedrate (this scrapes a float rather than an int)
- ensured args were passed to functions to keep them more general, and allow ease of testing
- moved functions out of YP into other parts of the codebase where they can be used more generally (e.g. the feedrate scrape can by called by job recovery in future) 
- moved location of scrape_last_feed_command in job data module in the hope that it's less likely to create merge conflict with job recovery later on
- Unit tests to ensure that functionality is good and working as expected :)
Tested via unit test, and by running main.py on computer
> scrape_last_feed_command and get_is_constant_feed_rate for YetiPilot

- src/asmcnc/apps/maintenance_app/widget_maintenance_brush_save.py
- src/asmcnc/apps/maintenance_app/widget_maintenance_brush_use.py
When checking whether get digital spindle info has been successful, ld_qda is now used instead of spindle production year, as ld_qda updates to an error value when spindle is disconnected whereas production year does not.
Additionally lengthened delay between writing protocol and checking values, to improve consistency.
Tested on rig and signed off by Benji
> Maintenance brush times new feedback

- src/asmcnc/comms/serial_connection.py
When a job is stopped, brush use values are no longer written if setting 51 is enabled
> Sc2 retain written brush use

- src/asmcnc/apps/maintenance_app/widget_maintenance_brush_save.py
- src/asmcnc/apps/maintenance_app/widget_maintenance_brush_use.py
When getting info, rather than waiting a fixed period of time and checking what has been received, instead poll the response repeatedly for 3 seconds before deciding that spindle is disconnected, to improve consistency.
Tested on rig
> Maintenance brush times poll info

- src/asmcnc/comms/router_machine.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
Tested bake on rig and in the warranty parts of ZHQC app
All distance/calibration stuff was made length neutral when working on Mini, so this change will be fine (and I had a quick look over the calibration app and where we look at shortbench/grbl max to make sure)
> Replace 2502 with 2503

- src/asmcnc/skavaUI/screen_stop_or_resume_decision.py
- tests/manual_tests/visual_screen_tests/screen_stop_or_resume_decision_test.py
When resuming job from pause screen, if job was paused due to yetipilot setting a low feed, yetipilot is now disabled.
Tested on windows with unit test
> Disable yetipilot when resuming from low feed pause

- src/asmcnc/skavaUI/screen_go.py
- src/asmcnc/skavaUI/screen_stop_or_resume_decision.py
When resuming a job after a pause, the job no longer automatically resumes, and instead the user is now required to press the resume button on the go screen to allow them time to adjust settings.
Tested on rig
> Stop auto resume after unpause

- src/asmcnc/core_UI/job_go/popups/popup_yetipilot_settings.py
For whatever reason, "disabling" the active toggle with standard kivy args doesn't seem to work on the rig (even though the graphic default is to be greyed out - very weird). 
Have set up the function to take in the "version" arg and then respond based on that. 
Tested on rig
> Yp settings toggle actual disabling

- src/asmcnc/comms/router_machine.py
Tested on rig using branch speed_overrides_test (which sends the +/-10% commands from the go screen widget)
> Add speed override functions for +/- 10%

- src/asmcnc/comms/serial_connection.py
- tests/automated_unit_tests/comms/test_serial_connection_process_grbl_push.py
Put this in instead of moving_in_z, as I can think of a few times when I would have used this in the past if I had thought of it. 
Tested with unit tests and running SW on rig.
> General tracking of x/y/z change, as generally useful

- src/asmcnc/skavaUI/widget_feed_override.py
- src/asmcnc/skavaUI/widget_speed_override.py
- Read percentages exclusively from Ov status part (ensures no mismatch)
- 0.06s delay instead of 0.05s
> Update override logic

- src/asmcnc/skavaUI/screen_job_recovery.py
When using scroll buttons in job recovery, the new selected line number is displayed in the line selection text input.
> Make line input match update during scroll

- src/asmcnc/apps/upgrade_app/screen_upgrade.py
- src/asmcnc/skavaUI/screen_lobby.py
Increased time between enabling spindle motor and sending get info protocol in the upgrade app, to improve consistency of info retrieval.
Tested on rig
> Upgrade screens data bug

- src/asmcnc/skavaUI/screen_job_recovery.py
- src/asmcnc/skavaUI/screen_nudge.py
- src/asmcnc/skavaUI/widget_z_move_nudge.py
When Z axis is supposed to raise to safe height on nudge screen entry and exit, the current position is checked to avoid lowering the Z axis unexpectedly. Additionally includes a bugfix for the nudge screen Z move widget, where I had forgotten to make it take the jog mode from the XY widget after I had moved the button
Tested on rig
> Job recovery stop lowering z

- src/asmcnc/skavaUI/screen_jobstart_warning.py
Just needed to reorder when flags were set and go screen entered. 
Tested on rig.
> Ensure shc resets before entering go screen

- src/asmcnc/comms/serial_connection.py
- tests/automated_unit_tests/comms/test_serial_connection_streaming_units.py
When I tried to test a fix for ZHQC, I was getting a failure from streaming the calibration files because the jigs have not been set up to use yp. 
Rather than adding yp module to apps that don't need it, I pulled out the instances of checking and setting use_yp into functions that check whether yp exists in the first place. 
Tested with unit tests.
Tested on rig; also made test branch `use_yp_test_none` for testing standard functions without yp, but it fell over before running the job (due to other screens not being able to reference yp through serial comms).
Merged this into the new branch for debugging ZHQC, and tested on that; this merge fixed the issue.
> Set up functions for checking and setting use_yp

- src/asmcnc/comms/serial_connection.py
One of the jigs in ZHQC stayed Idle after starting a job, which I suspect was caused by it thinking it was paused (possibly due to a door or something, I'm not sure). The other jig was fine. 
We ensure that machines are unpaused at the start of the job from the go screen; this "pause unset" has been put into the skeleton buffer stuffer (i.e. function used to stream jobs behind the scenes, like calibration files).
Tested ZHQC tuning/calibration on rig :)
> Ensure machine pause set to false when skeleton buffer stuffer is called

- src/asmcnc/production/z_head_qc_jig/z_head_qc_pcb_set_up.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_pcb_set_up_outcome.py
- tests/manual_tests/visual_screen_tests/z_head_qc_pcb_outcome_screen_test.py
Set: 
```
double_stack_single_driver_x_current = 31
double_stack_dual_driver_x_current = 27
default_z_current = 31
default_y_current = 28
```
Added in code to set, check, and report on setting of the Y current as well. 
Tested on Dev A through test specific branch [high_current_ZHQC_test](https://github.com/YetiTool/easycut-smartbench/tree/high_current_ZHQC_test) for use of port. 
Checked with main app that currents were getting changed & reported in current screen was same as set by ZHQC.
> Increase default currents to high values, and add in current change for Y axis

- src/asmcnc/apps/systemTools_app/screens/popup_system.py
- src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
Added 'Digital Spindle Test' button
On click shows popup:
Pressing confirm will run the spindle test.
Any issues will show up like this:
Functionality of the spindle test comes from ZHQC app.
Tested on rig, first with known good spindle then by unplugging spindle power cable to simulate fail.
> Spindle test in final test

- src/asmcnc/skavaUI/screen_file_loading.py
Added an error message to display to the user when they attempt to load a file with over 10 million lines
Tested on windows, in all languages
> Add error message for loading file with over 10 million lines

- src/asmcnc/comms/serial_connection.py
- tests/automated_unit_tests/comms/test_serial_connection_streaming_units.py
LED commands are now excluded from having line numbers added to them.
Tested using unit tests, and on rig with yetipilot enabled on a file with an LED command on it, ensuring that the LED colour is changed correctly
> Exclude leds

- src/asmcnc/apps/shapeCutter_app/screens/widget_sC31_z_height.py
Updated the Z height widget in the shapecutter app to stop it from appearing outside of the widget's limits
> Fix shapecutter Z height widget overflowing

- src/settings/settings_manager.py
When getting list of latest releases, the software no longer assumes that a beta release exists in the 10 latest releases, by first checking if one has been found before assigning it to a variable, instead of throwing an exception.
Tested on rig (by adding new tags locally until the latest beta release is more than 10 releases away, then checking that this causes an error on master, then making sure the software update works regardless on this branch)
> Catch error when beta release is not found

- src/asmcnc/comms/smartbench_flurry_database_connection.py
When we changed the variable that stores the job time a while back, it meant SmartManager wasn't receiving the job time. 
Tested on rig.
> use total_runtime_seconds as time job_time

- src/asmcnc/skavaUI/screen_go.py
Tested on dev machine by disabling health check and starting the job.
> Set YP widget to disabled, not failed if health check is disabled.

- src/asmcnc/apps/systemTools_app/screens/screen_final_test.py
- src/asmcnc/comms/router_machine.py
Needed to debug after soft reset at end of sequential stream caused issues in final test :)
Tested on machine with Barry to get sign off
Also tested setting serial number and $54 setting to make sure soft reset was happening as default
> Add reset_grbl_after_stream argument to write_dollar_setting function default is true. Call is as false from set x and y step functions

- src/asmcnc/comms/router_machine.py
On new machines the grbl homing pull off puts the position of the spindle clamping nut below the acrylic window and the level of the double stack motors, making it difficult to access immediately after homing. 
Rather than changing the GRBL pull off (which is a general setting that also affects the X and Y switches), adding a raise at the end of homing will only affect the Z axis. 
This change will apply to old machines as well. 
Also added some more comments around the homing code :) 
Tested on dev machines.
> Add Z raise to homing sequence

- src/asmcnc/skavaUI/screen_home.py
Commented out the button, but put the image id into an invisible float layout so that no change to main body of code is needed :) 
Tested on Dev B through VNC
> Hide job recovery button

- src/asmcnc/apps/maintenance_app/widget_maintenance_brush_save.py
- src/asmcnc/apps/maintenance_app/widget_maintenance_z_misc_save.py
Spindle settings screen was already swapped from previous pull request
> Swap positions of info and save buttons in maintenance app

- src/asmcnc/skavaUI/screen_go.py
All cases for various branches tested on rig. Test table in "Testing job start with/without soft reset" gsheet. 
Also tested a few job starts with lowered Z axis on job start, and conducted endurance testing with many_resumes branch to make sure that GRBL resume does not interrupt active moves (unlike GRBL soft reset).
> Stream resume after failed spindle health check to replace soft reset on screen entry. 

- src/asmcnc/apps/wifi_app/screen_wifi.py
I've tested it by switching between Yeti Wi-Fi and a personal hotspot and checking that the IP address has changed correctly and used `ping` to check Internet connectivity.
> Made network change without rebooting

- src/asmcnc/apps/wifi_app/screen_wifi.py
Weird or duplicate network names should no longer appear in the list of networks in the Wi-Fi screen. Tested on rig by changing the name of the hotspot on my phone to include special characters like \n, \t, \x00, etc
> Wifi ssid list

- src/asmcnc/keyboard/custom_keyboard.py
This makes the keyboard behave more like the default one.
- When multiline is set to false, the on_text_validate function is called instead of adding a newline
- The height of the keyboard is slightly smaller, so it doesn't cover up some text inputs, and adjusts based on window size
> Keyboard enter fix

- src/asmcnc/comms/router_machine.py
This affects: 
- Customer facing screens: 
- src/asmcnc/apps/maintenance_app/widget_maintenance_laser_buttons.py
- src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_35.py
- src/asmcnc/skavaUI/widget_common_move.py
- Production screens:
- src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc_warranty.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_1.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
Tested all customer facing buttons on rig and checked terminal output.
> Change generic spindle on function from S25000 to S12000

- src/asmcnc/keyboard/custom_keyboard.py
This ensures that all of the native functionality of the text input works as expected, and fixes issues including: 
- input_filter was not working (so letters could be entered in number fields) 
- cursor did not set where the text was added (it was always being added to the end of the line)
Tested on computer
> Use text input native insert text function

- src/asmcnc/keyboard/custom_keyboard.py
- tests/manual_tests/experiments/experiment_custom_keyboard.py
The generic_for_loop_alternative function will call the repeating function up to 10 times before the next frame of the application, and schedule the next 10 calls after the next frame. This is a bit more scalable than the loops, and guarantees that the UI won't lock on screens with a lot of text inputs. 
Also made a little manual test module for playing with the keyboard functions. 
Tested via test script, tested through EC on the computer, and tested on rig.
> Replace for loops in custom_keyboard module with kivy clock alternative

- src/asmcnc/keyboard/custom_keyboard.py
- tests/manual_tests/experiments/experiment_custom_keyboard.py
Fixes issue where backspace only removed letters from the end, not the cursor position. 
Tested with keyboard test module, and in sw running on PC.
> Refactor key_up with built in textinput functions

- src/asmcnc/comms/localization.py
Tested on PC and on rigs (in English & Korean & another European language)
> Move builder.load_string to only happen for korean characters

- src/asmcnc/skavaUI/screen_job_recovery.py
- src/asmcnc/skavaUI/screen_nudge.py
- src/asmcnc/skavaUI/screen_recovery_decision.py
Moves the exit cross up by 1 pixel on job recovery screens, to hide the thin background line above it.
Tested on rig
> Move exit cross up by 1 pixel

- src/main.py
Automatically detects the resolution of the screen on the raspberry pi's and defaults to 800x480 for all other operating systems.
Tested on laptop and console
> Automatically set screen resolution

- src/asmcnc/comms/localization.py
Tested on computer, ran all unit tests, and tested on rig (in Korean).
> Set up font paths so that unit tests can still work

- src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
Otherwise you can probe in the app, exit it, and still have a the necessary reminder in the home app disabled (because what you've probed in the app probably won't match what you want to do in the home screen). 
Tested on rig
> Remove disable probe reminder popup from drywall app widget

- src/asmcnc/production/database/calibration_database.py
- src/asmcnc/production/z_head_mechanics_jig/z_head_mechanics.py
- src/asmcnc/production/z_head_mechanics_jig/z_head_mechanics_booting.py
- src/asmcnc/production/z_head_mechanics_jig/z_head_mechanics_monitor.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
- src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
- src/lb_calibration_app.py
- src/lower_beam_qc_app.py
- src/z_head_mechanics_app.py
- src/z_head_qc_app.py
(and ensure production jigs have access to keyboard - they weren't running otherwise)
Production needs a way to enter custom dollar settings for warranty & older model ZHs asap. 
Tested on Mac
> Add grbl monitor to zh jig warranty screens

- src/main.py
Tested on computer, just makes testing a bit easier :)
> Update test cycle comment in main to use l.approved_languages instead of its own out-of-date list

- tests/manual_tests/visual_screen_tests/info_popups_test.py
- Has all of the customer facing info popups (excluding shapecutter)
- Can click through all of the popups to get to the next one
- Recommend updating this so that it language cycles through one popup version at a time (rather than going through all and then lang cycling) - suspect this would be easier to proof.
> Vlad's popup test file

- src/asmcnc/core_UI/job_go/popups/popup_yetipilot_settings.py
> Allowed health check image to stretch to scale on C10

- src/asmcnc/apps/maintenance_app/widget_maintenance_z_lubrication_reminder.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2584?atlOrigin=eyJpIjoiZGYxYTFlNjczMzljNGVlMzg4MDJhMWQyN2U2OTc3NDkiLCJwIjoiaiJ9)
> Implement scaling utils in update_label_font_size

- src/asmcnc/comms/localization.py
If it doesn't find a match, return the string from dict with punctuation.
> Localisation fix

- src/asmcnc/comms/localization.py
- src/asmcnc/comms/model_detector.py
- tests/automated_unit_tests/comms/test_localization_product_name.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2451)
I've updated the localisation module to replace any instance of "SmartBench" to "SmartCNC".
None
> Archie/dwt rebrand/2451

- src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2657)
Added labels next to text inputs on canvas widget
> Add labels to canvas text inputs

- src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
- src/asmcnc/keyboard/custom_keyboard.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2662?atlOrigin=eyJpIjoiZjAyZmVmYTRjMTYxNDBiM2E4Y2M2YTI2NzQxZjc1OTYiLCJwIjoiaiJ9)
The keyboard now comes up on the right and the numeric layout is narrower. One current issue is that the numpad comes up in the same position in the material popup as well.
> Added mechanism for setting a fixed keyboard position

- src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2667?atlOrigin=eyJpIjoiNTU4ZDQ3MjU5NzQ0NDhhZGI2YjU5Yzk0OGE5Yzk0NDIiLCJwIjoiaiJ9)
The function "update_text" is what performs all the necessary validation. All I did to it was remove the "if" statement and move everything back by one tab but git thinks I re-wrote the whole function again.
> Validating input after lose of focus

- src/asmcnc/comms/model_manager.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/jira/software/projects/YTSS/boards/1?assignee=5f8db15e6bc6340068c0bfc3&selectedIssue=YTSS-2681)
> Archie/dwt rebrand/smartbench name

- src/asmcnc/comms/grbl_settings_manager.py
- src/asmcnc/comms/model_manager.py
- src/asmcnc/comms/serial_connection.py
> start_sequential_streaming can now be called simultaneously

- src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
- src/asmcnc/core_UI/components/FloatInput.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2690)
Moved input_filter = 'float' from instanciation to the default FloatInput setup
> Change floatinput to set float type by default

- src/asmcnc/skavaUI/screen_local_filechooser.py
If machine is a drywall machine, it doesn't show the USB button in the filechooser.
> don't show usb in filechooser on DWT

- src/asmcnc/apps/systemTools_app/screen_manager_systemtools.py
When try to save or restore settings from and to usb, it crashed due to a exception in logger. I wonder how this would not crash with a simple print() but it is fixed now.
> fixed crash on save_/restore_settings

- src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2703?atlOrigin=eyJpIjoiZTlkNjkwNzBkN2Y4NDQ3MjgzNzhjZDUwYjhiMWVmMWYiLCJwIjoiaiJ9)
I moved the checks for the depth per pass error message to a separate function which is called on text change
> Depth per pass warning shows as you type

- src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
DWT will have a lower z_max_travel of 120mm. (normal double stack machines have 130). Factory screen takes care of that.
> set  z max travel dependent on machine type

- src/asmcnc/apps/systemTools_app/screens/widget_final_test_xy_move.py
In the widget there were print() statements, which were changed into Logger....()
> Remove logger calls

- src/asmcnc/apps/systemTools_app/screens/screen_build_info.py
Yes this is disgusting - Az's idea & he approved it
(the button still works) - for use in house. SSH still disabled on power cycle
> Set button opacity to 0

- src/asmcnc/core_UI/new_popups/popup_bases.py
The separator line for the job validation popup had slightly rounded edges. This makes the edges square.
> Fix rounded edge on separator line

- src/asmcnc/job/job_data.py
- tests/automated_unit_tests/job/test_generate_recovery_gcode.py
Spindle state gcode is now scraped earlier in job recovery, and placed before the Z movement and after the XY movement commands. This should fix an issue where the spindle hits the material before turning on.
Tested with unit test
> Add spindle state gcode before going to z position

- src/asmcnc/apps/drywall_cutter_app/engine.py
Disabled geberit shape datum offsetting. This behaviour was a hangover from an initially proposed approach for dwt logic.
None
> Disable geberit datum offset

- src/asmcnc/skavaUI/screen_local_filechooser.py
- src/asmcnc/skavaUI/screen_usb_filechooser.py
- src/jobCache/.gitignore
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3007)
Re-enabled USB filechooser on dwt machines. Both local and USB filechoosers now only display .dwt files on dwt machines.
> Allow dwt files to be loaded on dwt machines

- src/asmcnc/job/yetipilot/config/profiles.json
YetiPilot profiles for MDF with upcut cutters have been removed, as the tolerances were not as good as with alternative cutters. 
~- [ ] I have tested graphical changes on all languages~
~- [ ] I have updated the jira ticket~
~- [ ] I have updated documentation (if applicable)~
~- [ ] I have run the unit tests suite and they pass~
~- [ ] [#<pull_request_number>]~
Tested on Martha, checked that selecting MDF no longer brought up "upcut" option.
> Remove MDF upcut profiles

- src/asmcnc/job/yetipilot/config/profiles.json
Reinstated Birch plywood 6 mm 2 flute compression YP profile 
Typo caused this profile to go missing in v2.9.2 update
None
> Correct typo in profiles.json

- src/asmcnc/comms/router_machine.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-2976)
Set internal spindle on variable off when cancelling stream, to stop button flashing when spindle is disabled without using the button.
> Set internal spindle on variable off when cancelling stream

- src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
- src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3067)
Replaced unit switch with 'mm' label in shapes
> Replace unit switch with mm label

- src/asmcnc/skavaUI/widget_speed_override.py
[Jira Ticket]()
On go screen, speed down button is disabled if close to minimum RPM.
> Disable speed down button if close to threshold

- src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3072)
When set to inside toolpath, minimum size of shape is validated to account for toolpath diameter.
> Account for tool diameter in min labels

- src/asmcnc/comms/serial_connection.py
[Jira Ticket](https://yetitoolsmartsoftware.atlassian.net/browse/YTSS-3058)
Stopped setting spindle on variable when in check state
> Don't set spindle on variable when in check state

- src/asmcnc/apps/systemTools_app/screens/screen_beta_testing.py
On downgrade, the config files will be deleted to not cause a crash on boot. Tested on a rig downgrading to 2.9.0 and checking startup still works, then changing to feature/shapes_lite and checking shapes still works.
> Purge configs on downgrade
